uPortal-Project/uportal-app-framework

- src/main/webapp/css/angular.less
- src/main/webapp/css/buckyless/beta-header.less
- src/main/webapp/css/buckyless/myuw-toolkit-temporary.less
- src/main/webapp/frame.jsp
+ Wrap everything with a `my-uw` class, not just the content
> MUMUP-2029 : Fix less to have my-uw covering everything

- src/main/webapp/portal/main/partials/header.html
in addition, avoid some screen reader read out "my uiow"
> MUMUP-2045 add description for MyUW logo

- .gitignore
Just a little help from your friends still using Eclipse.
> Ignores Eclipse generated files

- src/main/webapp/portal/main/controllers.js
Logic for determining whether to show the popup to a user and handling legacy local storage variables. @timlevett does this cover every use case you were thinking of?
> MUMUP-2060:: Clean splash seen-ness

- src/main/webapp/frame.jsp
- src/main/webapp/portal/features/partials/features.html
- src/main/webapp/portal/main/partials/main.html
- src/main/webapp/portal/main/partials/sidebar-left.html
- src/main/webapp/portal/misc/partials/portlet-header.html
- src/main/webapp/portal/search/partials/search.html
- src/main/webapp/portal/settings/partials/settings.html
Add aria-landmark role usages in support of accessibility.
> MUMUP-2078 Home : aria-landmark role usages -[uw-frame]

- src/main/webapp/css/buckyless/notifications.less
- src/main/webapp/portal/notifications/partials/notifications-full.html
Includes:
- More stylish notifications
- x instead of garbage icon
- Tooltip on hover over dismiss icon
In Action:
> MUMUP-2062: Notification style

- src/main/webapp/js/app-config.js
- src/main/webapp/portal/main/controllers.js
+ Set default to `[]`
+ Only do stuff if stuff to do
+ Disable by default
> MUMUP-2087 : cleanup features null state

- .gitignore
- src/main/webapp/portal/notifications/services.js
- src/main/webapp/portal/notifications/spec/notification_services_spec.js
- src/main/webapp/portal/storage/services.js
+ Changed behavior so instead of empty string it'll return an empty array on an empty state of the notification:dismiss KV.
+ Created test case to make sure that stays that way
+ Documentation for storage service
> MUMUP-2110 : Fix empty string issue with value, add in test

- src/main/webapp/css/buckyless/header.less
- src/main/webapp/portal/search/partials/search.html
> MUMMNG-1947: Fix top search bar button styling

- src/main/webapp/css/buckyless/sidebar.less
- src/main/webapp/portal/main/partials/sidebar-left.html
+ Remove unneeded z-index
+ Move popover to bottom
Resolves #26
> Fix popover z-index issue

- src/main/webapp/portal/notifications/controllers.js
- src/main/webapp/portal/notifications/partials/notifications-full.html
+ Fix empty state for the dismissed tab
+ Add in an undo dismiss action
_note my mouse capture was a little off, but all is well_
> MUMUP-2141 : Add in undismiss

- src/main/webapp/frame.jsp
- src/main/webapp/js/app-config.js
- src/main/webapp/portal/main/controllers.js
- src/main/webapp/portal/main/partials/header.html
- src/main/webapp/portal/main/partials/sidebar-left.html
+ `APP_FLAG.hideSidebar` : Hides sidebar and sidebar pill. Also sets default sidebar to hidden so it'll hide
+ `APP_FLAG.hideSearch` : Hides search bar in header
I think you can imagine what that looks like.
> MUMUP-210[7-8] : Hide flags for hiding things

- src/main/webapp/config.js
- src/main/webapp/js/app-config.js
- src/main/webapp/portal/misc/services.js
- src/main/webapp/portal/notifications/controllers.js
+ Add in documentation on how to properly utilize the misc service
+ Add in `.min` to a bunch of libraries we utilize (drops 1mb (from 2.3mb to 1.3mb)
+ Add in a page hit for notifications
> Doc Misc service, minify all the things

- src/main/webapp/portal/misc/directives.js
- src/main/webapp/portal/misc/partials/circle-button.html
- src/main/webapp/portal/settings/partials/settings.html
+ Added a `<circle-button>` demo to /settings
+ Added `disabled` flag to circle-button directive
+ Added `title` parameter which gives you the option of showing a title below
+ Documented the directive
> Add in disabled and title, documented

- src/main/webapp/css/buckyless/header.less
- src/main/webapp/js/app-config.js
- src/main/webapp/portal/main/controllers.js
- src/main/webapp/portal/main/partials/header.html
- src/main/webapp/staticFeeds/sidebar.json
> MUMUP-2156 : Add a logout link to header when sidebar is hidden

- src/main/webapp/portal/main/partials/header.html
- src/main/webapp/portal/notifications/directives.js
- src/main/webapp/portal/notifications/services.js
+ Fix issue with notification dismiss service getting called 3 times during init page load
+ Fix issue with clicking on the menu item for notification (in xs) and the menu not hiding after partial loading.
> MUMUP-2013 : Notification xs fix multiple service calls

- src/main/webapp/bower.json
See https://github.com/UWMadisonUcomm/uw-ui-toolkit/releases/tag/v0.3.2 for details on this.  Basically for the fa change
> MUMUP-2142 : upgrade uw-ui-toolkit

- src/main/webapp/frame.jsp
- src/main/webapp/js/app-config.js
- src/main/webapp/portal/main/controllers.js
- src/main/webapp/portal/main/partials/sidebar-left.html
Hopefully this will give us better insights into user behavior regarding the sidebar - whether people use it, how often they minimize it and maximize it, which links they are clicking in the navigation...
@timlevett, did I use your nifty `pushGaEvent()` function correctly? Is there a way I can test this locally?
> MUMUP-1926: Add google analytics tracking for sidebar events

- src/main/webapp/portal/main/controllers.js
add $rootScope.GuestMode in mainController
> prepare for MUMUP-2070 

- src/main/webapp/js/app-config.js
- src/main/webapp/portal/main/controllers.js
+ Moves guest username to constants
+ Check if user object exists before accessing it.
> Minor cleanup of guest mode for more generic guest username

- src/main/webapp/portal/storage/services.js
Due to https://github.com/UW-Madison-DoIT/KeyValueStore/pull/11 this needs to change.
> KEYVALUE-5 : update to storage 2.0.0

- src/main/webapp/portal/notifications/services.js
- src/main/webapp/portal/storage/services.js
Noticed that needed to tweak it a bit more.
> Fix storage issue for 2.0.0

- src/main/webapp/portal/main/controllers.js
Discovered it was from changes here #52.
> Minor fix to put MISC_URLS in scope

- src/main/webapp/js/app-config.js
- src/main/webapp/portal/main/controllers.js
- src/main/webapp/portal/main/partials/sidebar-left.html
- src/main/webapp/portal/search/controllers.js
+ `angularjs-portal` needs to not refresh the page completely when it goes "home"
+ Move `SEARCH.isWeb` to `APP_FLAGS.isWeb`. Makes more sense to me this way
> Fix issue with home going to / for angularjs-portal

- src/main/webapp/WEB-INF/web.xml
- src/main/webapp/js/app-config.js
- src/main/webapp/my-app/main.js
- src/main/webapp/portal/main/controllers.js
- src/main/webapp/portal/main/partials/access-denied.html
- src/main/webapp/portal/main/route.js
- src/main/webapp/portal/main/routes.js
Based on the writings of one @keirserrie (http://staging-2.uc.wisc.edu/my-uw/#coarse-grain-access), I give you the basic access denied page.
> MUMUP-2123 : template for access denied

- src/main/webapp/portal/misc/directives.js
- src/main/webapp/portal/misc/partials/circle-button.html
See https://github.com/UW-Madison-DoIT/angularjs-portal/pull/351
> Truncate circle button text after 24 characters

- src/main/webapp/css/buckyless/general.less
- src/main/webapp/portal/misc/partials/circle-button.html
Created a CB specific style as the other ones were inconsistent depending on where you had cb.
> Add in cb specific styling

- src/main/webapp/config.js
Tested on 2G connection, loaded successfully in 47 seconds :)
> MUMUP-2248 : Remove 7 second timeout

- src/main/webapp/css/loading.css
- src/main/webapp/frame.jsp
> Sandy background, faster transition

- src/main/webapp/css/loading.css
- src/main/webapp/frame.jsp
- src/main/webapp/portal/main.js
- src/main/webapp/portal/main/directives.js
- src/main/webapp/portal/main/partials/body.html
- src/main/webapp/static.html
+ Moved most of body to `<uw-body>` directive
+ Moved static stuff to `static.html` (noscript, loading state, old browsers)
+ Fixed loading state for `noscript` people
+ Fixed state for old browsers
+ Remove loading.css as it was taking time to load (ironic?)
> MUMUP-2266 : Cleanup loading state, and rearrange some assets

- src/main/webapp/js/ga.js
- src/main/webapp/portal/features/controllers.js
+ Clean up when the href = `javascript:;`
+ Add log when we do an outbound link
+ Add page view for `/feature`
> Fix some odd ga stuff

- src/main/webapp/css/buckyless/header.less
- src/main/webapp/js/ga.js
- src/main/webapp/portal/features/controllers.js
> Fix mobile header height

- src/main/webapp/karma.conf.js
This is more for downstream applications that want to use this karma file.
> Add in my-app module to preprocessors for coveralls coverage reports

- src/main/webapp/js/app-config.js
- src/main/webapp/js/frame-config.js
- src/main/webapp/portal/main/controllers.js
- src/main/webapp/portal/main/partials/header.html
- src/main/webapp/portal/search/partials/search.html
- src/main/webapp/portal/settings/partials/settings.html
Resolves #89 
+ Moved most theme naming to the theme constant
+ Cleaned up header, search
+ `NAMES.title` is now the app name
+ Removed not needed NAMES constaints
> Issue 89 : cleanup NAMES.title to be only app name

- src/main/webapp/portal/search/controllers.js
Goes with https://github.com/UW-Madison-DoIT/angularjs-portal/pull/358.
Now the search field shows the thing you're searching for when you're on that page, doesn't everywhere else.
> MUMUP-2286: Search field populated on search results page, and nowhere else

- docs/js/app-config.js
- docs/markdown/directives.md
- docs/my-app/home/partials/demo.html
- docs/my-app/home/partials/doc-home.html
- docs/my-app/home/route.js
- docs/my-app/main.js
- uw-frame-components/portal/settings/partials/settings.html
+ Moved demos to a demo page in docs (was in settings page in the product)
+ Documented `Loading Gif`
+ Cleaned up padding a bit on the doc pages.
> Cleanup demos

- docs/js/app-config.js
- uw-frame-components/js/app-config.js
- uw-frame-components/portal/main/controllers.js
- uw-frame-components/portal/main/partials/footer.html
I know we said we didn't want to do a constant with an array, but I did it anyway. It was too easy to pass up.
+ Removed `whatsNewURL` as it was only used by the footer (and for frame we set it to null anyway)
+ Added `FOOTER_URLS` array constant. Pretty simple url, target, title
+ For frame apps I left it like it is today, just feedback and help.
> MUMUP-2296 : Update footer

- package.json
- uw-frame-static/build.sh
- uw-frame-static/superstatic.json
resolves part of #102 for static content pages
> Add in serverside rewrites, change to superstatic

- docs/base-rerouter.html
- docs/build.sh
- docs/demo/index.html
- docs/home/index.html
- docs/index.html
- docs/markdown/README.md
- docs/markdown/directives.md
- docs/markdown/home.md
- docs/markdown/versions.md
- docs/my-app/home/controllers.js
- docs/my-app/home/partials/demo.html
- docs/my-app/home/partials/doc-home.html
- docs/my-app/home/partials/md.html
- docs/my-app/home/route.js
- docs/my-app/main.js
- docs/superstatic.json
+ Remove `html5mode` for documentation. gh-pages doesn't support server side rewrites and having a dynamic base is hard.
+ Add in some files for proper redirects when they hit root of `gh-pages` (redirects to latest)
> Version documentation

- .gitignore
- docs/markdown/home.md
- docs/markdown/releasing.md
- docs/markdown/versions.md
- uw-frame-java/pom.xml
+ Added in documentation about releasing
+ cleaned up pom.xml for java releases
> Document release SOP

- uw-frame-components/css/buckyless/header.less
- uw-frame-components/css/buckyless/responsive.less
This reduces the DL size from 1.3mb to 1.0mb
> Remove madison.jpg from mobile burger bar

- README.md
- docs/markdown/releasing.md
- package.json
+ Restyled the readme a bit
+ Added some more badges (BADGE ALL THE THINGS!!!)
+ Restructured npm package to have the proper information
> Npm package for components

- docs/markdown/home.md
- docs/markdown/theming.md
+ Add in current status of theme support
> MUMUP-2249 : Theme support documentation

- docs/markdown/buttons.md
- docs/markdown/coarse-grain-access.md
- docs/markdown/configuration.md
- docs/markdown/home.md
- docs/markdown/quickstart.md
- docs/markdown/tables.md
- docs/markdown/text-guidelines.md
- docs/markdown/widgets.md
- docs/my-app/home/controllers.js
- docs/my-app/home/partials/doc-home.html
- uw-frame-components/js/app-config.js
+ Moved stuff from http://staging-2.uc.wisc.edu/my-uw/
+ Updated documentation where needed
+ Took documentation about widgets from gist written forever ago
+ Wrote document about quickstart
+ Updated the doc's home
+ documented `app-config`
> MUMUP-2289 : Documentation is a thing

- uw-frame-components/css/buckyless/header.less
- uw-frame-components/portal/main/partials/username.html
> Remove picture image for now

- uw-frame-components/css/buckyless/app-header.less
- uw-frame-components/css/buckyless/header.less
- uw-frame-components/portal/misc/partials/app-header.html
> MUMUP-2320: Align name dropdown with options dropdown

- uw-frame-components/css/buckyless/general.less
- uw-frame-components/css/buckyless/header.less
- uw-frame-components/css/buckyless/widget.less
Not much to this, but I added some padding along the sides of the home page and in the name dropdown to give them some breathing room.
Before: 
After:
> Add padding to sides of home page and name dropdown

- docs/markdown/configuration.md
- uw-frame-components/js/app-config.js
- uw-frame-components/js/frame-config.js
- uw-frame-components/my-app/main.js
- uw-frame-components/portal/main.js
- uw-frame-components/portal/misc/services.js
- uw-frame-components/portal/notifications/services.js
- uw-frame-components/portal/settings/controllers.js
- uw-frame-components/staticFeeds/groups.json
- uw-frame-java/src/main/webapp/frame.jsp
- uw-frame-static/index.html
+ Add in themes by group
+ Add in `defaultTheme` support
+ Cleaned up theme naming
+ Made the `PortalGroupService` but didn't end up using it for this (There is a long story here, but I'll save you 5 minutes of reading)
+ Enhanced the beta settings selection of theme to persist for that session
+ Made uw-system theme the default
> MUMUP-2327 : Make themes by group and persist across the whole session

- uw-frame-components/js/ga.js
> Preserve window name for external links

- docs/markdown/configuration.md
- uw-frame-components/js/app-config.js
- uw-frame-components/portal/main.js
- uw-frame-components/portal/main/services.js
- uw-frame-components/staticFeeds/loginsuccess.json
- uw-frame-components/staticFeeds/session.json
- uw-frame-static/superstatic.json
+ During loading if a recent login is not detected (last 4h) then it does a silent login via `/portal/Login?silent=true`. 
+ The response is JSON, which we store in the `$sessionStorage.portal` object. username, lastLoginMills, and theme.
+ During a fetch to `session.json` it gets a different username that is stored in `$sessionStorage.portal.username` it will throw a redirect to the login page
+ By default the silent login on load is disabled (as most apps won't do this, but `angularjs-portal` will)
+ Documented all new `app-config.js` entries in configuration.md. Lucky enough, if you don't want to use this feature, then just don't configure any of the new entries.
> MUMUP-2334 : Silent login on load

- uw-frame-components/js/ga.js
- uw-frame-components/portal/misc/services.js
+ Delete old version of GA
+ Use new GA in config setup
+ Change outbound links to new GA
+ Events now work.
> MUMUP-2360 : Fix events

- uw-frame-components/staticFeeds/features_template.json
Added in some notes to cleanup some gotchas
> Cleanup feature template to be real

- uw-frame-components/css/buckyless/responsive.less
Goes with https://github.com/UW-Madison-DoIT/angularjs-portal/pull/399
> Responsive marketplace styles

- uw-frame-components/portal/main.js
- uw-frame-components/portal/main/controllers.js
Adds in a check to see if you are a guest during silent login. This should remove edge cases where user isn't loaded yet but we want to check for `$rootScope.GuestMode`
> Guest mode revisited

- uw-frame-components/portal/search/controllers.js
I need to be able to update the global search from the search results controller. By adding this watch we can do just that.
> MUMUP-2366 : Make search field updateable from another controller

- docs/js/app-config.js
- docs/markdown/configuration.md
- uw-frame-components/js/app-config.js
- uw-frame-components/portal/features/controllers.js
- uw-frame-components/portal/features/services.js
- uw-frame-components/portal/misc/services.js
- uw-frame-components/portal/misc/spec/portal_group_service_spec.js
- uw-frame-components/staticFeeds/features.json
- uw-frame-components/staticFeeds/features_template.json
+ Add in filtering function to the `PortalGroupService`
+ Add in filtering to features feature
+ Moved configuration for features to its own constant (app-config change required)
```diff
var config = angular.module('app-config', []);
config
.constant('APP_FLAGS', {
-            'features' : false,
'showSearch' : false,
'isWeb' : false
})
.constant('SERVICE_LOC', {
'sessionInfo' : 'staticFeeds/session.json',
-            'featuresInfo' : 'staticFeeds/features.json',
'notificationsURL' : 'staticFeeds/notifications.json'
})
.constant('NAMES', {
@@ -25,6 +23,11 @@ define(['angular'], function(angular) {
'groupFiltering' : false,
'notificationFullURL' : 'notifications'
})
+        .constant('FEATURES', {
+            'enabled' : false,
+            'groupFiltering' : false,
+ …
```
> MUMUP-2318 : Features by group

- docs/markdown/configuration.md
- uw-frame-components/config.js
- uw-frame-components/js/app-config.js
- uw-frame-components/js/override.js
- uw-frame-components/portal/main.js
This is round 2 of `override.js` based on recommendations in #141. Resolves #99
Basically we change everything in `app-config.js` to `.value` instead of `.constant`. Then we have a function that goes through the `OVERRIDE` constant and updates anything that it needs to. Arrays are appended to.
> App config override round 2

- uw-frame-components/portal/main/partials/username.html
_disregard the fact that no bell after, just didn't have it enabled in uw-frame_
> MUMUP-2423 : Guest mode for user option dropdown

- uw-frame-components/portal/features/controllers.js
- uw-frame-components/portal/main/partials/header.html
- uw-frame-components/portal/notifications/controllers.js
- uw-frame-components/staticFeeds/guest-session.json
+ No features for you GuestMode
+ No notifications for you GuestMode
> Add in flags so notification and features don't show for GuestMode

- uw-frame-components/css/buckyless/general.less
> fix issue with footer being stomped on by page

- uw-frame-components/js/frame-config.js
> fix uwm theme

- uw-frame-components/css/buckyless/notifications.less
- uw-frame-components/portal/notifications/controllers.js
- uw-frame-components/portal/notifications/partials/notification-bell.html
- uw-frame-components/portal/notifications/partials/notifications-full.html
+ Don't show priority banner on notification page
+ Show ! triangle and highlight the border with color1 for priority notifications
> MUMUP-2440 : General cleanup of priority notifications on notification page

- .gitignore
Tiny PR for the IntelliJ users out there.
> Ignore IntelliJ generated files

- docs/markdown/widgets.md
- uw-frame-components/bower.json
- uw-frame-components/css/buckyless/directives/app-header.less
- uw-frame-components/css/buckyless/header.less
- uw-frame-components/css/buckyless/responsive.less
- uw-frame-components/css/buckyless/widget.less
- uw-frame-components/portal/features/controllers.js
- uw-frame-components/portal/features/partials/announcement.html
- uw-frame-components/portal/main/partials/username.html
- uw-frame-components/portal/misc/partials/app-header.html
- uw-frame-components/portal/notifications/partials/notifications-full.html
- uw-frame-components/portal/search/partials/search.html
Copy of #171 but merge requested for 3.0.0 branch instead
> upgrade ui-bootstrap to 1.2.1 from 0.13.4

- uw-frame-components/css/buckyless/inner-nav.less
Before: 
After:
Relates to https://github.com/UW-Madison-DoIT/hrs-portlets/pull/57
> MUMUP-2428 : make the color red for active

- uw-frame-components/portal/main/partials/header.html
> MUMUP-2421 : Adds back popup feature

- docs/markdown/widgets.md
Now that angularjs-portal has a docs page we don't need this here.
> MUMMNG-2414 : remove myuw specific stuff

- uw-frame-components/css/buckyless/widget.less
+ Removed pointer when nothing to click
+ Added ability to make anchor a block element so you don't need the p tag
+ Added ability to remove hover highlight
> MUMUP-2474 : Cleanup widget styles for .widget-list

- docs/markdown/configuration.md
- uw-frame-components/js/app-config.js
- uw-frame-components/portal/main/controllers.js
- uw-frame-components/portal/main/partials/body.html
- uw-frame-components/static.html
We are encouraging uw-frame apps to no longer show the back to MyUW old in the footer.
> MUMMNG-2404 Turning off old my.wisc

- uw-frame-components/css/buckyless/directives/app-header.less
- uw-frame-components/css/buckyless/footer.less
- uw-frame-components/css/buckyless/general.less
- uw-frame-components/css/buckyless/header.less
Added a little shadow to main elements (header, footer, white background, app-header) to give the page a little depth.
> Add a little depth to the main elements on the screen

- docs/markdown/home.md
- docs/markdown/material.md
Beginning to put together some documentation on how we'll use Material. This is a place to put any Material components we use in MyUW, quick links to their documentation, and anything worth noting about how we use them or how we develop with them.
> Start Material docs

- uw-frame-components/css/buckyless/directives/app-header.less
- uw-frame-components/css/buckyless/responsive.less
Arrows now match up and I can sleep at night
Before
after
> cleanup position of app-header popover

- uw-frame-components/css/buckyless/buttons.less
- uw-frame-components/css/buckyless/general.less
- uw-frame-components/js/frame-config.js
- uw-frame-components/portal/notifications/controllers.js
- uw-frame-components/portal/settings/partials/setting-option.html
- uw-frame-components/staticFeeds/sample_notifications.json
+ Add in disable notification filter,
+ Fix flat buttons to be the same size as outline buttons, 
+ changes settings to be flat/outline buttons and cleanup box shadow on cards
> Disable Notification Filter Beta Flag

- docs/markdown/configuration.md
- docs/my-app/home/partials/demo.html
- uw-frame-components/css/buckyless/base.less
- uw-frame-components/css/buckyless/general.less
- uw-frame-components/js/app-config.js
- uw-frame-components/js/frame-config.js
- uw-frame-components/my-app/main.js
- uw-frame-components/portal/main/partials/example-page.html
- uw-frame-components/portal/main/partials/username.html
- uw-frame-components/portal/notifications/services.js
- uw-frame-components/portal/notifications/spec/notification_services_spec.js
- uw-frame-components/portal/settings/controllers.js
- uw-frame-components/portal/settings/directives.js
- uw-frame-components/portal/settings/partials/settings.html
- uw-frame-components/portal/settings/partials/user-settings.html
- uw-frame-components/portal/settings/route.js
- uw-frame-components/portal/settings/routes.js
- uw-frame-components/portal/storage/services.js
- uw-frame-static/superstatic.json
+ Adds in user settings page
+ Adds in logic to delete keys from `/storage`
+ Cleaned up the beta card
+ Cleaned up the example page
+ Removed some nothing classes (classes that were being used, but had no definition in our less)
> MUMUP-2487 : Way to clear dismissed ids

- uw-frame-components/staticFeeds/guest-session.json
- uw-frame-components/staticFeeds/session.json
Didn't find any uses where it was bound to views.
> fix: correct misspelled 'surName' field

- uw-frame-components/portal/main/partials/username.html
As a screen reader user, I would like my screen reader to let me know the account dropdown menu exists, so that I can exercise that menu.
add 'role' and 'aria-label'
> MUMUP-2508 Screen reader does not read account menu

- uw-frame-components/portal/settings/partials/user-settings.html
Copy edits settings text introduced in #213.
> Copy edits on last-seen ID resetting

- uw-frame-components/js/app-config.js
- uw-frame-components/portal/notifications/services.js
Change defaults so `/storage/` and the notifications are enabled by default. This will provide a more streamlined experience for the user.
> MUMUP-2500 : and you get a notification

- uw-frame-components/js/app-config.js
- uw-frame-components/portal/settings/partials/user-settings.html
Let's users reset their layout via the settings page.  Even uses the reset zone.
OH NO!!  I deleted all my favorites!!  Better use the reset button.
That's better
> MUMUP-2588 Lnks reset-my-layout from usr settings

- uw-frame-components/bower.json
- uw-frame-components/config.js
- uw-frame-components/css/buckyless/header.less
- uw-frame-components/portal/main.js
- uw-frame-components/portal/main/partials/example-page.html
- uw-frame-static/index.html
+ Add in angular material 1.0.9
+ Create a theme for uw-madison (obviously needs theme per portal theme)
+ Fixed minor style issue with padding in the search (style from material)
+ Added cards to the example page
> Inject angular material

- uw-frame-components/portal/main/partials/header.html
> If search is disabled, disable it for mobile also

- uw-frame-components/portal/notifications/controllers.js
Fixes npe with notification controller when no notifications are returned from the service
> Fix NPE in notification controller

- docs/markdown/material.md
- docs/markdown/theming.md
- uw-frame-components/js/frame-config.js
- uw-frame-components/portal/main.js
+ Documentation for material themes
+ Add ability to select a pre-existing palette
+ Created basic themes for each school
[![theme demo](https://img.youtube.com/vi/WIHrFNUotLs/0.jpg)](https://www.youtube.com/watch?v=WIHrFNUotLs)
> MUMUP-2498 : Material themes for all

- uw-frame-components/portal/features/partials/announcement.html
> Fix alignment of action links in announcements

- uw-frame-components/css/angular.less
- uw-frame-components/css/buckyless/features.less
- uw-frame-components/css/buckyless/general.less
- uw-frame-components/css/buckyless/header.less
- uw-frame-components/css/buckyless/helpers.less
- uw-frame-components/css/buckyless/md-generated.less
- uw-frame-components/portal/misc/partials/add-to-home.html
- uw-frame-components/portal/search/partials/search.html
In this PR:
- Added CSS outside of the my-uw scope that applies to md-menus
- Buttons in menus now appear consistently across all themes
- Removed inline styles from `search` directive
> Fix appearance of buttons in md-menus

- uw-frame-components/css/buckyless/widget.less
This issue was pointed out during MyUW dev meeting. Easy fix.
> Widget launch buttons use primary theme color on hover

- uw-frame-components/css/buckyless/general.less
Fix for [MUMUP-2693](https://jira.doit.wisc.edu/jira/secure/RapidBoard.jspa?rapidView=121&view=detail&selectedIssue=MUMUP-2693)
> Fix appearance of unordered lists in IE

- uw-frame-components/css/buckyless/notifications.less
> Change link color if someone has more than one number one priority

- uw-frame-components/css/buckyless/notifications.less
- uw-frame-components/portal/main/partials/header.html
> Cleanup burger menu button and notification bell

- uw-frame-components/portal/features/controllers.js
Apparently unseen is only one word, right @paulerickson?
> Correct spelling of unseen in mascot announcements

- uw-frame-components/portal/features/controllers.js
Yet another race condition check.
> Add more checks for guest mode for annoucements

- uw-frame-components/css/buckyless/notifications.less
- uw-frame-components/portal/notifications/controllers.js
- uw-frame-components/portal/notifications/partials/notification-bell.html
- uw-frame-components/staticFeeds/sample_notifications.json
> MUMUP-2721 : Add in dismiss to priority notifications

- uw-frame-components/portal/notifications/services.js
- uw-frame-components/portal/notifications/spec/notification_services_spec.js
+ Fixed bug where if you had dismissed notification ids in your array, the sortNotifications wouldn't know about them until it was to late (promises)
+ Added test case to verify the dismissed is populated properly.
> Clean up promises on notification service

- uw-frame-components/portal/features/services.js
- uw-frame-components/staticFeeds/features.json
Changing the services.js file to take in a iso time and then convert it back to epoch so it doesn't mess up the flow of the rest of the code.
Changes will be made to the features.json file accordingly to send in an iso time instead of epoch.
> MUMUP-2716 : Model Mascot announcement end date in friendly format

- package.json
- tools/uw-frame-static/build.js
- uw-frame-components/css/angular.less
- uw-frame-java/pom.xml
I also ran into https://github.com/UW-Madison-DoIT/uw-frame/issues/338 about 70% of the time when I was on wireless, but almost 0% of the time when I was wired.
This also takes the idea of compiling all the less in one spot from : https://github.com/UW-Madison-DoIT/uw-frame/pull/340/ while keeping the version numbering that we are currently using.
> Issue 338 - Fixes cdn error and uses npm for less compiling

- docs/markdown/overview.md
- uw-frame-components/portal/about/partials/about.html
- uw-frame-components/portal/main/partials/access-denied.html
- uw-frame-components/portal/main/partials/beta-header.html
- uw-frame-components/portal/main/partials/file-not-found.html
- uw-frame-components/portal/main/partials/footer.html
- uw-frame-components/portal/main/partials/server-error.html
- uw-frame-components/portal/misc/partials/circle-button.html
- uw-frame-components/portal/misc/partials/launch-button.html
- uw-frame-components/portal/notifications/partials/notification-bell.html
- uw-frame-components/portal/notifications/partials/notifications-list-item.html
- uw-frame-components/static.html
PR to go hand in hand with https://github.com/UW-Madison-DoIT/angularjs-portal/pull/552
> MUMUP-2705 Address href noopener and no referrer vulnerability

- uw-frame-components/portal/main/partials/username.html
[MUMUP-2801](https://jira.doit.wisc.edu/jira/browse/MUMUP-2801)
> Fix duplicate text of items in username menu

- docs/markdown/versions.md
> Link v3.0.2 docs, release notes.

- docs/_layouts/default.html
- Fixes octocat image (did search for other images)
- Fixes the return to home link
> MUMUP-2831 Misc fixing of doc links

- README.md
- docs/text-guidelines.md
- Added text/typography guidance for notifications to the text and typography best practices doc
- Added instructions to run the docs locally to the base project's README
> Update best practices doc, add local Jekyll instructions

- uw-frame-components/js/frame-config.js
Switching help url from the base KB page to a "Getting Help with MyUW System Portal" page.
----
> MUMMNG-3243 Changing help url for uw-system schools

- docs/README.md
- docs/widgets.md
> Add minimum documentation for using the new widget feature

- uw-frame-components/portal/widgets/controllers.js
- Supports ordering leave balances by value
> Add sorter function to allow sorting strings as numbers

- uw-frame-components/portal/widgets/controllers.js
Fixes bug where rss widget was always reporting error.
----
> MUMUP-2898 Fixes bug with RSS widget

- uw-frame-components/portal/widgets/controllers.js
> Add temporary logging to troubleshoot sorting

- uw-frame-components/css/buckyless/widget.less
Just a quick adjustment I left out in the last PR!
> Adjust styles for RSS widgets

- docs/README.md
- docs/contributors.md
Gratefully acknowledge contributors.
----
> Acknowledge contributors.

- appveyor.yml
Enables continuous integration testing on Windows, may assist with investigating #349 
Example build output: https://ci.appveyor.com/project/ChristianMurphy/uw-frame/build/1.0.2
----
> Issue #349: Test on Windows

- uw-frame-components/portal/widgets/services.js
Adds error text to unauthorized widget appearing in layout. 
----
- [X ] This Contribution is under the terms of Individual [Contributor License Agreements][] (and also Corporate Contributor License Agreements to the extent applicable) appearing in the [Apereo CLA roster][].
> Adds Error message to unauthorized widget.

- uw-frame-components/css/buckyless/header.less
- uw-frame-components/portal/main/partials/username.html
menu off the bottom of the avatar, header underneath click catcher
----
> MUMMNG-3332 "annoying" menu

- package.json
- uw-frame-components/css/lib/less-1.6.2.js
- uw-frame-components/js/ga.js
3rd party libraries should be ignored from linting to minimize upgrade troubles
----
> reverting and ignoring 3rd party libraries from linting

- package.json
- uw-frame-components/js/sortable.js
it looks like sortable is another 3rd party copy
----
> ignore sortable

- README.md
- docs/buttons.md
- docs/directives.md
- docs/quickstart.md
- docs/releasing.md
- docs/theming.md
Add code block syntax flags.
Escape literal `_` characters in markdown.
Update example theme to used valid JSON double quotes.
----
> Documentation Syntax Highlighting

- package.json
- uw-frame-components/portal/features/services.js
- uw-frame-components/portal/main.js
- uw-frame-components/portal/main/controllers.js
- uw-frame-components/portal/misc/services.js
- uw-frame-components/portal/notifications/services.js
- angular/typecheck-array
- angular/typecheck-object
- angular/typecheck-string
----
> fixing eslint angular/typecheck rules

- package.json
- uw-frame-components/portal/main.js
removes private route call
----
> ESLint fix angular/no-private-call

- package.json
- uw-frame-components/js/app-config.js
- uw-frame-components/js/frame-config.js
- uw-frame-components/karma.conf.js
- uw-frame-components/my-app/main.js
- uw-frame-components/portal/about/controllers.js
- uw-frame-components/portal/about/services.js
- uw-frame-components/portal/features/controllers.js
- uw-frame-components/portal/features/services.js
- uw-frame-components/portal/main.js
- uw-frame-components/portal/main/controllers.js
- uw-frame-components/portal/main/directives.js
- uw-frame-components/portal/main/services.js
- uw-frame-components/portal/misc/controllers.js
- uw-frame-components/portal/misc/directives.js
- uw-frame-components/portal/misc/filters.js
- uw-frame-components/portal/misc/services.js
- uw-frame-components/portal/misc/spec/portal_group_service_spec.js
- uw-frame-components/portal/notifications/controllers.js
- uw-frame-components/portal/notifications/services.js
- uw-frame-components/portal/notifications/spec/notification_services_spec.js
- uw-frame-components/portal/search/controllers.js
- uw-frame-components/portal/settings/controllers.js
- uw-frame-components/portal/storage/services.js
- uw-frame-components/portal/timeout/controllers.js
- uw-frame-components/portal/timeout/services.js
- uw-frame-components/portal/widgets/controllers.js
- uw-frame-components/portal/widgets/services.js
- uw-frame-components/test/main.js
cropping lines to under 80 chars
----
> fixing eslint max-len

- uw-frame-components/portal/features/services.js
rejecting promises rather than throwing errors.
----
> fixing errors and not returning reasons

- uw-frame-components/portal/main/partials/header.html
I think our styleguide would have us prefer sentence case for tooltips.
----
> Use sentence case in tooltips.

- docs/skinning.md
- docs/theming.md
Adds a step-by-step skinning exercise for use in helping developers get quickly up to speed on adding a theme. 
----
- [X ] This Contribution is under the terms of Individual [Contributor License Agreements][] (and also Corporate Contributor License Agreements to the extent applicable) appearing in the [Apereo CLA roster][].
> Adds skinning exercise to docs folder

- docs/skinning.md
Fixes linting errors.  If we mark code as javascript, linting picks it up and makes sure it's valid.
Automating linting been failing for a day or so
----
> Fixes skinning.md lint errors

- docs/README.md
Changes the text on a link in the documentation to explain that the link really goes to how to run locally and how to make a uPortal Framework App.
----
> Expands the quickstart link text from the main README

- uw-frame-components/js/app-config.js
- uw-frame-components/portal/notifications/services.js
- uw-frame-components/staticFeeds/groups.json
> Enables notifications to work in static frame

- uw-frame-components/css/buckyless/features.less
- uw-frame-components/css/buckyless/md-generated.less
- uw-frame-components/portal/features/partials/features.html
- Fixed some weird styling choices and mismatched background color
- Simplified image markup and styles (images won't stretch to display larger than natural size)
- Added app icon for features page
----
> Improve appearance of features page

- .github/CONTRIBUTING.md
- CODE_OF_CONDUCT.md
We're an Apereo project, so Welcoming Policy applies. Acknowledge this, thereby picking up 25% more points on our Community insight score.
----
> Acknowledge Apereo Welcoming Policy

- uw-frame-components/js/app-config.js
- uw-frame-components/portal/main/controllers.js
- uw-frame-components/portal/main/partials/username.html
- uw-frame-components/portal/settings/controllers.js
- uw-frame-components/portal/settings/partials/user-settings.html
Adds functionality to opt out of avatar photo
----
> Opt out av

- uw-frame-components/css/buckyless/widget.less
- uw-frame-components/css/themes/default-variables.less
- uw-frame-components/portal/widgets/partials/type__action-items.html
> using css for action-items, md-colors didn't work well with themes

- uw-frame-components/staticFeeds/sample-widget__list-of-links.json
Changes demo widget to use aries proxy
----
- [ x] This Contribution is under the terms of Individual [Contributor License Agreements][] (and also Corporate Contributor License Agreements to the extent applicable) appearing in the [Apereo CLA roster][].
> Uses aries proxy

- docs/make-a-widget.md
+ Guide to use sentence case for list items and for launch button text.
+ Link app directory documentation in support of widget authoring.
+ Other copy edits.
----
> Guide towards sentence case

- SUPPORT.md
Direct people towards asking questions on the uPortal mailing list.
Adapted from the Angular support file. https://github.com/angular/angular-cli/pull/7082
See https://github.com/blog/2400-support-file-support for github support.
----
> docs(github): Add SUPPORT.md to guide questions to the mailing list

- uw-frame-components/portal/messages/partials/announcement-popup-template.html
- uw-frame-components/portal/messages/partials/notifications-bell.html
- Replace hard-coded `href`
- Add accessibility suggestions from @apetro's comments on #502
----
> Add missing URL and aria label

- docs/messaging-implementation.md
- uw-frame-components/portal/messages/controllers.js
- uw-frame-components/portal/messages/filters.js
- uw-frame-components/staticFeeds/sample-messages.json
Adding functionality to implement an Add To Home button to feature announcements.
----
> Feature button

- uw-frame-components/portal/messages/partials/notifications-list-item.html
fixed bug where urls were not resolved in list view
urls weren't resolved in notification list view.  This fix corrects that.
Tracked at UW-Madison with MUMMNG-3820
----
> fix(messages): fix url in list view

- README.md
additional badges provide at-a-glance information on how the project is doing and how to interact with the project.
Changes:
* group badges into sections
+ add more project status badges
+ add project standards badges
- remove code climate badge
----
> docs(readme): add additional project status badges

- uw-frame-components/portal/messages/controllers.js
- uw-frame-components/portal/messages/filters.js
- uw-frame-components/portal/messages/partials/announcement-mascot.html
Adds a check to the AddToHome button to see if the widget is already added to the layout
----
> Add home button

- components/portal/widgets/controllers.js
- components/portal/widgets/partials/type__time-sensitive.html
- Fixed a typo that was causing partial content to show
- Added a fallback so partial content never shows
- Some comments on widget template
----
> fix: Fix typo and prevent partial content from showing

- README.md
> docs(readme): Updating badge to fully qualified name

- CHANGELOG.md
- README.md
- components/portal/about/partials/about.html
- components/portal/misc/partials/example-options.html
- docs/README.md
- docs/_includes/footer-aside.html
- docs/announcements.md
- docs/app-options.md
- docs/configuration.md
- docs/contributors.md
- docs/injecting-dependencies.md
- docs/latest/README.md
- docs/latest/index.html
- docs/messaging-implementation.md
- docs/quickstart.md
- docs/releasing.md
- docs/skinning.md
- docs/theming.md
- docs/versions.md
- package-lock.json
- package.json
- pom.xml
updating to current location in github
----
> update old uw-frame github links

- package-lock.json
- package.json
remove redundant 'uportal' from scoped npm package
----
> build: rename scoped package

- pom.xml
using webapp.target.directory for the copy jobs, and setting the staging server id to what [oss-parent](https://github.com/sonatype/oss-parents/blob/master/oss-parent/pom.xml#L54) specifies
----
> build: clean up pom variables

- README.md
- committers.md
> docs: Project renamed

- components/portal/search/controllers.js
- components/portal/search/directives.js
- components/portal/search/partials/search.html
We're not using type ahead, so the code is just getting in the way.
----
> fix(search): instancing and removing a typeahead from search controller

- package-lock.json
- package.json
> chore(package): update eslint-plugin-compat to version 2.0.1

- components/css/buckyless/footer.less
https://github.com/uPortal-Project/uportal-app-framework/pull/588 clobbered change.
This is basically this, again - https://github.com/uPortal-Project/uportal-app-framework/pull/587
----
> fix: circle character between footer links

- components/portal/messages/controllers.js
- components/portal/messages/filters.js
- components/portal/messages/services.js
- docs/messaging-implementation.md
Allows an optional titleUrl parameter to call an api and retrieve text to display in a notification. If the api comes back empty, the notification is not displayed
----
> MUMUP-3044 Call api to get message text

- components/portal/messages/controllers.js
Fix bug where group filter disables all filtering. 
----
> fix: filter for group retrieves data

- CHANGELOG.md
> docs: include another example of downstream effects

- CHANGELOG.md
This demonstrates another way of coping with the update.
----
> docs: add another change to the log

- CHANGELOG.md
- components/portal/messages/controllers.js
- components/portal/messages/services.js
- docs/messaging-implementation.md
MUMUP-3209 Removes the "filter by title" functionality until that's ready to deploy. Fixes bug where notifications are not properly filtering by group/ 
----
> Filter groups

- CHANGELOG.md
Update changelog to reflect newly released version 7.0.0
----
> docs(changelog): update changelog to reflect 7.0.0

- components/portal/main/partials/footer.html
- components/portal/main/partials/main-menu.html
#625 
- Track clicks on the sidenav footer links
- Fix aggravating use of single quotes in HTML attributes
----
> feat: track clicks on sidenav footer links

- components/portal/messages/controllers.js
- components/portal/messages/filters.js
MUMUP-3148: Filters messages for validity beteween goLive and expireDate
----
> feat(messages): filter messages by date

- components/portal/widgets/directives.js
> feat: add analytics to widget interactions

- CHANGELOG.md
+ prefer talking in terms of apps in third person rather than in terms of what "you" are using and "your" apps.
+ remove "Removed" section from pending unreleased changelog, since we're not using that section to document removing things. :smile:
+ wrap at 80 characters
----
> docs(changelog): copy edits

- .github/PULL_REQUEST_TEMPLATE.md
+ Add a checklist item to the Pull Request template to remind to update CHANGELOG
This idea arose from MyUW Scrum team 2018-02-05 Retrospective discussion, looking to better capture breaking changes and keep the changelog up to date.
Resolves MyUW-local [MYUWADMIN-335](https://jira.doit.wisc.edu/jira/browse/MYUWADMIN-335).
----
> docs: remind in PR template to update CHANGELOG.md

- components/portal/main/partials/header.html
+ Remove reference to an icon that looks to me to be absent from the markup.
+ Avoid a "MyUW" in the comment in favor of talking about the portal title generically.
----
> docs: rm stray icon reference, generalize MyUW reference

- CHANGELOG.md
- components/portal/messages/controllers.js
fixes bug where add to home logic short-circuited external links
----
> fix: external links in mascot announcements now work

- CHANGELOG.md
- package-lock.json
Updates lockfile so npm 5+ can leverage new versions in package.json
----
> chore(package): update package lock file

- CHANGELOG.md
- components/portal/main/partials/body.html
- components/portal/misc/controllers.js
- components/portal/misc/controllers.spec.js
- components/portal/misc/partials/frame-page.html
- package-lock.json
Angular was doing things to the original skip to main content link, where it wouldn't work if you had already followed the link once.  This allows the link to be followed as many times as a user would like.
----
> fix: Skip to Main Content only works on first link follow : MUMUP-3296

- CHANGELOG.md
updates changelog for 9.0.0
----
> chore: update changelog for next release

- docs/upgrading.md
provides updating instructions for major release
----
> chore: updates updating.md for major release

- CHANGELOG.md
- README.md
+ Add CII badge (we're not yet "passing", maybe 80% of the way there.)
+ Re-organize badges
It's a lot of badges. I think this helps make them slightly more digestable.
----
> Add CII badge

- CHANGELOG.md
- docs/make-a-widget.md
Document the dynamic `list-of-links` feature with example of the expected format of the dynamic `list-of-links` content response.
----
> docs: further document dynamic list-of-links feature

- CHANGELOG.md
> style(changelog): rm trailing whitespace

- CHANGELOG.md
- package-lock.json
- package.json
> chore(package): update stylelint to version 9.1.3

- CHANGELOG.md
- components/config.js
- components/portal/main.js
- Remove jQuery UI Sortable
----
> Remove jQuery ui sortable dependency

- CHANGELOG.md
We didn't actually run the 9 release to completion, so this is updating the changelog to reflect current changes.
----
> docs: update 9.0.0 release docs

- CHANGELOG.md
- components/portal/settings/partials/user-settings.html
adds resetters to the user-settings page
----
> feat: adds resetters to user-settings page

- CHANGELOG.md
adds comparator from 9.0.0 to 9.0.1 to changelog
----
> chore: changelog cleanup

- CHANGELOG.md
(Trivial).
----
- NA Updates `CHANGELOG.md` to reflect this PR's change.
> style: trim trailing whitespace

- components/portal/messages/controllers.js
removes unneeded service call 
----
> fix: removes unneeded service call

- .gitignore
- .vscode/settings.json
- CHANGELOG.md
- components/portal/widgets/partials/type__list-of-links.html
changes List Of Links limit to 6
----
> fix: change link limit to 6

- CHANGELOG.md
- components/css/buckyless/widget.less
> style: fix list of links buttons clipping

- CHANGELOG.md
- components/config.js
- components/portal/main/controllers.js
https://github.com/angular/angular.js/blob/master/CHANGELOG.md#security-related
https://github.com/angular/angular.js/blob/master/CHANGELOG.md#172-extreme-compatiplication-2018-06-12
https://github.com/angular/angular.js/blob/master/CHANGELOG.md#170-nonexistent-physiology-2018-05-11
https://github.com/angular/angular.js/blob/master/CHANGELOG.md#160-rainbow-tsunami-2016-12-08
Replace call to `angular.lowercase`, which has been removed, with `String.prototype.toLowerCase`
----
> chore: update angular to version 1.7.2

- package.json
> chore(package): update less to version 3.7.1

- CHANGELOG.md
Narrower for easier reading, better GitHub behavior, etc.
----
> style(changelog): wrap at 80 char where feasible

- CHANGELOG.md
> docs: update changelog for v10.1.0

- CHANGELOG.md
- components/portal/messages/partials/announcement-mascot.html
Addresses [issue flagged by axe](https://dequeuniversity.com/rules/axe/3.0/button-name?application=AxeChrome) on `img` element.
----
> fix(a11y): aria-label mascot image

- .travis.yml
- CHANGELOG.md
- appveyor.yml
- package-lock.json
https://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable
----
> ci: leverage npm ci to speed up testing

- CHANGELOG.md
Fix trivial typo in CHANGELOG.
----
- n/a Updates `CHANGELOG.md` to reflect this PR's change.
> docs(changelog): fix typo "leverate" --> "leverage"

- package-lock.json
> chore: sync package lock with package json

- CHANGELOG.md
- docs/upgrading.md
Updating changelog and upgrade guide for 11.0.0
----
> docs: update changelog for 11.0.0

- CHANGELOG.md
- components/portal/messages/controllers.js
- components/portal/messages/filters.js
> fix: revert messages to previous state

- CHANGELOG.md
- components/static.html
[MUMUP-3446](https://jira.doit.wisc.edu/jira/browse/MUMUP-3446): "As a person using Internet Explorer to access MyUW, I would like to be made aware that my experience is not going to be a good one and that it would be much more satisfactory if I used a different browser."
- Show dialog during application bootstrapping to prompt browser switch/upgrade
- Provide link to KB article to help with browser upgrade
- Hidden by default
- Displayed only if user agent contains keywords from IE 11 or earlier
----
> feat: ask IE users to upgrade browsers

- CHANGELOG.md
- docs/upgrading.md
Update changelog, upgrade docs to reflect 12.0.0 release.
----
> Prep 12.0.0 release

- CHANGELOG.md
- components/staticFeeds/about-page.json
Add link to MyUW news to `about-page.json`
----
> feat: add link to MyUW news

- CHANGELOG.md
- components/head-static.html
Avoid reliance on unpkg yet still get the "latest-compatible-with-1.0.0" abstraction by sourcing `myuw-help-link` from `static`.
----
> Source myuw-help-link from /static

- CHANGELOG.md
- components/head-static.html
This version addresses some concerns about vertical alignment and includes the `confirming-callback` attribute support.
----
> chore: upgrade banner component version

- CHANGELOG.md
- docs/injecting-dependencies.md
- Tweak "injecting dependencies" page to describe exact process I just had to go through :)
- Add some extra detail
----
> docs: tweak dependencies documentation

- CHANGELOG.md
I intend to cut a 12.1.0 release today. This updates the changelog to reflect.
----
> Prepare changelog for 12.1.0 release

- CHANGELOG.md
- components/config.js
- components/head-static.html
Picks up a bunch of little bugfixes.
----
> fix: upgrade to angular-material 1.1.19 from 1.1.11

- CHANGELOG.md
- package-lock.json
- package.json
We want to use all the fonts. All of them. 
----
> update font awesome version

- components/portal/widgets/controllers.js
had been a remnant from development
----
- N/A Updates `CHANGELOG.md` to reflect this PR's change. (Bogus logging had been introduced since prior release, so removing it isn't a chane vis a vis prior release.)
> fix: remove excess bogus error logging

- CHANGELOG.md
- components/head-static.html
- components/portal/main/partials/example-page.html
Add a localhost demo of the new compact card web component.
----
> feat: demonstrate using new compact card web component

- CHANGELOG.md
- docs/releasing.md
Tightening up releasing documentation; updating changelog with hyperlinks supporting the 13.0.0 release.
----
> Tighten releasing docs

- components/portal/main/partials/header.html
Update MyUW Help dialog's title to "Help with MyUW".
> Update title of MyUW Help Dialog

- components/head-static.html
Update imported version of MyUW Help Web Component to 1.5.2
> Update imported version of MyUW Help Web Component to 1.5.2

- committers.md
[Paulina has been contributing](https://github.com/uPortal-Project/uportal-app-framework/commits?author=nogalpaulina) to uPortal-app-framework and should be recognized as a Committer, able to merge changes and publish releases.
See also in context of uPortal-home: https://github.com/uPortal-Project/uportal-home/pull/904 .
----
- N/A The change has been examined for security impact.
----
Tracked internally to MyUW as [MYUWADMIN-962](https://jira.doit.wisc.edu/jira/browse/MYUWADMIN-962).
> docs(committers): recognize Paulina Nogal as committer

- CHANGELOG.md
- components/head-static.html
- components/portal/main/partials/main-menu.html
- package-lock.json
- package.json
See [Jira ](https://jira.doit.wisc.edu/jira/browse/MUMMNG-5020
)page.
+ Upgrade myuw-profile web component to version 1.6.3
+ Remove `hide-xs` in `main-menu.html` to prevent hiding the myuw-profile on mobile on the drawer/left hand menu - we want it there all time
+ Run `npm audit fix` to fix some vulnerabilities in node modules
----
> chore: finish task MUMMNG-5020

- CHANGELOG.md
- components/head-static.html
+ Update import path to use latest unpkg version
----
> Myuw profile revision 2

- CHANGELOG.md
- components/portal/main/controllers.js
- components/portal/main/partials/main-menu.html
- package-lock.json
- package.json
I am pretty sure this issue is caused by incorrect passing of global variables in the controller of myuw-profile.  
I think (not 100% sure, couldn't test locally) my changes can fix the issue, although a better fix is probably needed to prevent future cases of this issue.
> Fix empty href of sidenav myuw-profile logout button

- CHANGELOG.md
- components/portal/main/controllers.js
Check session info to identify if user is a guest to display a bubble vs login button
----
> Check session info to identify if user is a guest

- CHANGELOG.md
- components/css/buckyless/header.less
- components/head-static.html
- components/portal/main/partials/header.html
- package-lock.json
- package.json
+ Update component `myuw-notifications` to v1.3.0
+ Fix the bug when using `myuw-nofitications`, showing the bell even messages are disabled
+ Fix styles on `myuw-nofitications`
> Fix myuw-notifications bugs

- CHANGELOG.md
- components/config.js
- components/js/overlay-config.js
- docs/configuration.md
- pom.xml
Adds the overlay-config feature innovated locally in MUMAA apps, so that this feature is in the framework available to all apps upon upgrade.
----
> add overlay-config

- CHANGELOG.md
- components/head-static.html
- components/portal/main/partials/header.html
- components/portal/main/partials/main-menu.html
+ Update `myuw-notifications` to v1.3.4
- [x ] The change has been examined for security impact.
- [ x] Updates `CHANGELOG.md` to reflect this PR's change.
- [x ] This Contribution is under the terms of Individual [Contributor License Agreements][] (and also Corporate Contributor License Agreements to the extent applicable) appearing in the [Apereo CLA roster][].
> Update myuw-notifications to v1.3.4

- CHANGELOG.md
- components/css/buckyless/md-generated.less
- components/head-static.html
+ Update `myuw-notifications` to v1.4.0
+ Update `myuw-banner` to v1.2.1
----
> Update versions of notifications and banner web components

- package-lock.json
- package.json
Upgrading less in efforts to get the build to work as built in Jenkins.
----
> upgrade less to 3.12.2 from 3.8.1

- CHANGELOG.md
- components/head-static.html
Update myuw-banner to v1.2.2
----
> Update myuw-banner to v1.2.2

- CHANGELOG.md
- components/head-static.html
- components/static.html
> Implement Snippets for the MyUW Tag Manager Account

- docs/make-a-widget.md
[MYUWADMIN-662](https://jira.doit.wisc.edu/jira/browse/MYUWADMIN-662)
> fix maintenance mode docs

- CHANGELOG.md
- components/css/buckyless/header.less
- components/head-static.html
- components/portal/main/partials/header.html
+ Update `myuw-search`to v.1.5.2
+ Update `myuw-notifications` to v.1.4.1
+ Update `myuw-profile` to v.1.6.5
+ Add `myuw-feedback` v.1.0.2
----
> Update Web Components versions

- CHANGELOG.md
- components/head-static.html
+ Update `myuw-search`to v.1.5.3
----
> Update myuw-search to v1.5.3

- CHANGELOG.md
- components/head-static.html
+ Update `myuw-search`to v.1.5.4
+ Update `myuw-app-bar` to v.1.7.2
----
> Update myuw-serach and myuw-app-bar

- CHANGELOG.md
- components/head-static.html
- components/portal/main/partials/header.html
> Temporarily removing myuw-feedback web component

- CHANGELOG.md
- components/head-static.html
- components/js/app-config.js
- components/portal/main/partials/header.html
- docs/configuration.md
+ Re-adding myuw-feedback web component with conditional flag feature
----
> Re-adding myuw-feedback web component with conditional flag feature

- CHANGELOG.md
- components/head-static.html
> Update version of myuw-search component to 1.5.5

- CHANGELOG.md
- components/head-static.html
> Use myuw-banner version 1.2.4

- components/portal/main/partials/example-page.html
- components/staticFeeds/sample-widget__list-of-local-links.json
> docs(examples): add widgetConfig-sourced list-of-links example

- CHANGELOG.md
- components/js/app-config.js
- components/portal/settings/controllers.js
- components/portal/settings/partials/user-settings.html
- components/portal/settings/services.js
+ Add feature flag to check which layout is used and utilize new boolean values to conditionally display Reset layout option.
+ Create new newLayoutResetService service to handle layout reset.
> Reset new layout

- components/portal/settings/controllers.js
When layout reset succeeds, show a dialog advising user that re-login will ensue and reminding how to escape settings page.
> show mdDialog when layout reset succeeds

- CHANGELOG.md
- components/css/buckyless/md-generated.less
Make tooltip text more accessible by adding contrasting background to it
----
> Tooltip style

- CHANGELOG.md
- components/portal/main.js
- components/static.html
Remove additional startFade so that the skeleton content fades out on hiding.
----
> Remove additional startFade to avoid delay on interacting with content

- CHANGELOG.md
- components/head-static.html
Update MyUW Profile import version to v.1.6.6
----
> Update MyUW Profile import version to v.1.6.6

- CHANGELOG.md
- components/head-static.html
- components/portal/main/controllers.js
Include lastName to be passed into myuw-login event listener
----
> Include lastName to be passed into myuw-login event listener

- components/css/buckyless/widget.less
> Fix mismatched closing curly braces

- CHANGELOG.md
- components/css/buckyless/md-generated.less
- components/head-static.html
+ Remove max-width from tooltips
+ Updates `myuw-help` to v.1.5.5
----
> Updates  myuw-help to v.1.5.5

- CHANGELOG.md
- components/head-static.html
> Update myuw-feedbback version

- CHANGELOG.md
- components/css/buckyless/md-generated.less
> Adjust height and line-height of the tooltip for better readability
