README.md, src/main/webapp/css/buckyless/myuw-toolkit-temporary.less, src/main/webapp/portal/main/partials/main.html, src/main/webapp/portal/misc/directives.js, src/main/webapp/portal/misc/partials/portlet-header.html
+ Added `app-collapse` to the `portlet-header` directive, default `false`. Sets the default state of the header
+ Added `app-show-toggle` to the `portlet-header` directive, default to hidden. Toggles if a toggle button shows in the header.
=> Make a collapsable header

src/main/webapp/bower.json
+ v0.3.1 of the uw-ui-toolkit has a fix to the .center class
+ This updates to that version
_Note that this screenshot is from angularjs-portal which utilizes the uw-frame_
=> MUMUP-2042 : update to latest uw ui toolkit

src/main/webapp/portal/misc/directives.js, src/main/webapp/portal/misc/partials/circle-button.html
We use circle buttons a lot, lets just make a directive. I give you `<circle-button>`.
Options:
+ href : the href you want the anchor to have
+ target : the target (if blank, it'll launch in same window)
+ fa-icon : the fa-icon you want to use (e.g. fa-star)
Here is a demo:
=> Add in circle button directive

pom.xml, src/main/webapp/frame.jsp, src/main/webapp/js/app-config.js, src/main/webapp/portal/features/controllers.js, src/main/webapp/portal/features/partials/features.html, src/main/webapp/portal/features/services.js, src/main/webapp/portal/main/controllers.js, src/main/webapp/portal/main/partials/footer.html, src/main/webapp/portal/main/partials/header.html, src/main/webapp/portal/main/partials/sidebar-left.html, src/main/webapp/portal/main/spec/main_controller_spec.js, src/main/webapp/portal/notifications/controllers.js, src/main/webapp/portal/notifications/partials/notification-bell.html, src/main/webapp/portal/notifications/partials/notifications-full.html, src/main/webapp/portal/notifications/partials/notifications.html, src/main/webapp/portal/search/controllers.js, src/main/webapp/portal/search/directives.js
+ Features cleanup. Added empty state, changed `MyUW` to `{{NAMES.title}}`, and polished controller.
+ Namespaced a bunch of controllers and a few services (prefix with Portal). This is due to angular having global scope on controller names. Should resolve #30 
+ negated the hide[Sidebar|Search] to be show[Sidebar|Search] to avoid double negative. This requires a minor release so bumped the version.
=> Cleanup v2

src/main/webapp/css/buckyless/notifications.less, src/main/webapp/portal/main/partials/header.html, src/main/webapp/portal/notifications/controllers.js, src/main/webapp/portal/notifications/directives.js, src/main/webapp/portal/notifications/partials/notification-bell.html, src/main/webapp/portal/notifications/partials/notifications-full.html
+ Add `mode` to the `<notification-bell>` directive
+ `mode='mobile-menu'` will result in    
+ `mode='bell'` and it'll show the bell `(used in the desktop nav bar)`
+ `mode='mobile-bell'` will result in a cute little notification badge on your burger menu `iff unread count > 0)`
+ Also fixed GA pageview with using mode. If `directiveMode` is not set in the notification controller (which it won't be on `notification-full.html`) then it'll do a page hit, otherwise it just carry's on.
+ I also (cough) shrunk the header in `notifications-full.html`
Based on mockups from Keir that are in the MUM > Notification folder of Google Drive
=> MUMUP-2013 : notifications in xs mode

src/main/webapp/portal/main/partials/footer.html
Some apps override `SERVICE_LOC.sessionInfo` the URL to customize the name in the side bar and build version in the footer. 
We don't know the serverName, nor do we have the portal sessionKey, so the JSON response for our custom URL doesn't include those values.
In the current uw-frame release, this results in the dashes between those fields rendering, and looking pretty funny:
This pull request makes a small tweak to the footer to only show those dashes when the respective fields are set. Results in no more funny looking dashes:
=> Hide '-' spans for serverName and/or sessionKey if not set

src/main/webapp/portal/settings/partials/settings.html
Reminds that the feature works only for compact-mode widget cards.
=> MUMUP-2207 Tweaks the /web-portlet-rendering flavor text.

src/main/webapp/portal/main/partials/sidebar-left.html, src/main/webapp/staticFeeds/sidebar.json
Resolves #51.
Prior to this change set, the links for Home and Log out in the sidebar came from the array returned by the URL defined in `SERVICE_LOC.sidebarInfo`. 
In this change set, the Home and Log out links in the sidebar are always there; Home is hard set to '/' (with target="_self", so it's not the route /, but the real path /), and Log out is configured via `MISC_URLS.logoutURL`.
A new horizontal rule appears below, and links are created from the array returned by the URL defined in `SERVICE_LOC.sidebarInfo` underneath.
In action:
=> Make Home and Log out non-overridable via sidebar

src/main/webapp/portal/main/partials/header.html
Needs `target='_self'` because the link is pretty much guaranteed to not be an angular route.
=> Log out link for showSidebar=false needs different 'target' attribute

src/main/webapp/portal/main/directives.js, src/main/webapp/portal/main/partials/main.html, src/main/webapp/portal/misc/directives.js, src/main/webapp/portal/misc/partials/frame-page.html
Creates a basic `<frame-page>` directive that you can pass in header information. It utilizes `<portlet-header>` for the header and `ng-transcude` for the body. This should promote similar pages.
I rewrote the main.html page in frame to show as an example
=> MUMUP-2123 part 1: Create basic frame page

src/main/webapp/frame.jsp, src/main/webapp/portal/main/controllers.js
For science!  And https://github.com/UW-Madison-DoIT/uw-frame/issues/60
Creates class on ng-view by appending slugified to the word route, such as `class="route-settings"` or `class="route-parent-child-grandchild"`
Resolves #60
=> ngView route-based class

src/main/webapp/frame.jsp
Minor bug fix on the route class. `ng-class` evaluates the thing provided, if you add `{{}}` it will try to evaluate twice, and the second time it'll be a string with `-` in it, then angular vomits.
Related to #64
=> Minor glitch on ng-class.

src/main/webapp/frame.jsp, src/main/webapp/portal/main/partials/header.html, src/main/webapp/portal/misc/partials/portlet-header.html
Banner is used for site-wide elements ( red bar on top ), heading for heading section of a page ( large image + app title ), application with title ( on ng-view, specific to app ) to describe the app.  In tests, we were NOT getting the app title read out ( @jiayinjx - right? ); this fixes that, but further testing is needed.
=> Change a few aria roles and add title

README.md
Documents that `uw-frame` is available in the Central Repository.
This in response to the question coming up of where one can get that Maven artifact.
=> Link presence in the Central Repository from README.

.gitignore, .travis.yml, README.md, package.json, src/main/webapp/.gitignore, src/main/webapp/js/app-config.js, src/main/webapp/karma.conf.js, src/main/webapp/package.json
+ Copied `package.json` from webapps dir to base. Needed still in webapps dir so that other projects can use it when running there tests
+ Added coveralls.io configuration into karma using the `karma-coveralls` package
+ added `npm test` to the travis ci scripts
=> MUMUP-2255 : Coveralls support for uw-frame

src/main/webapp/js/app-config.js, src/main/webapp/portal/main/partials/header.html
Go home frame app, you're drunk.
Note for release notes
`
To upgrade add rootURL to miscURLS and give a url to go to when the crest is clicked.
If no rootURL is provided, the application will instead go to it's context root like it does currently.
Suggested : 'rootURL' : '/web'
`
=> MUMUP-2263 Adds in root url to go back home

src/main/webapp/WEB-INF/web.xml, src/main/webapp/css/buckyless/general.less, src/main/webapp/my-app/main.js, src/main/webapp/portal/main/partials/access-denied.html, src/main/webapp/portal/main/partials/server-error.html, src/main/webapp/portal/main/routes.js
This pull request is intended to address issue #85. It adds a route/view that could be display for 500 class errors and service issues.
Example:
=> Add '/server-error' route and view

uw-frame-components/portal/features/partials/announcement.html
Sentence-case the "Not interested" control on the Bucky pop-up.
Before:
After:
Responds to @prtreige feedback from today's [sprint review](https://wiki.doit.wisc.edu/confluence/display/MUM/Sprint+070+Review+Meeting).
=> Sentence case "Not interested" ala "Tell me more".

package.json, uw-frame-static/build.sh
There were some issues in package.json preventing `npm run static` from working out of the box, which this PR should resolve:
1.  bower and http-server dependencies are declared
2.  `npm run build-static` runs before `npm run static`
3.  ';' is replaced with '&&' in shell scripts so that non-zero error codes are not ignored (i.e., if you can't go into a directory, report failure, and _don't_ start deleting things or running http-server)
=> Fix up npm scripts

Gruntfile.js, package.json, uw-frame-static/build.sh, uw-frame-static/index.html
Resolves #102 , replaces #105. Basically the same thing, this just happens at build time.
See https://www.npmjs.com/package/grunt-processhtml for details on the `processhtml` task.
=> static.html injection at build time of static

uw-frame-components/css/buckyless/header.less, uw-frame-components/css/buckyless/responsive.less
Before: 
After:
For now we can't really update the placeholder text, because our search results don't show people or web results yet, so I left the text as is. @keirserrie let me know if you think something else would be better for the text in the meantime.
You'll notice the crest is a bit larger and moved up and left, so it overflows on both sides. I think this looks better, but open to opinions.
Also, fixed mobile so it looks better:
Before:
After:
=> MUMUP-2202: Update home page search bar, make mobile search look better, improve crest and title

uw-frame-components/css/buckyless/header.less
If someone has a really short first name, the site header popover looks funky. This fixes that.
=> Style tweak for popover for site header

uw-frame-static/build.sh
Our docker container build slaves run as root. This is apparently a problem for `bower install`
=> Fix bower install so that it can be ran a root, if one was so inclined

uw-frame-components/css/buckyless/buttons.less
Edge case, to be sure :
Bootstrap provides .btn-link to style buttons as links.  This fixes their hover state.  By the way, LOVE having the My UW styles here instead of in the toolkit.
=> Btn link hover state fix

uw-frame-components/css/buckyless/widget.less
In commit 6f49e392f3177c656fdf62deafe9e2d3b6cd785d it was recommended to switch the background color of widgets to `#fff`. A great suggestion, but it created some issues with widgets in myuw. I'm going to create a story to do this but in addition, adjust the other things that are in widgets, like inputs.
Before
After
=> revert part of  6f49e392f3177c656fdf62deafe9e2d3b6cd785d

docs/config.js, docs/js/config.js, docs/markdown/configuration.md, docs/markdown/ga.md, docs/markdown/home.md, uw-frame-components/bower.json, uw-frame-components/config.js, uw-frame-components/portal/features/controllers.js, uw-frame-components/portal/main.js, uw-frame-components/portal/misc/services.js, uw-frame-components/portal/notifications/controllers.js
+ Add in angulartics
+ Add in a @\deprecated on method `miscService. pushPageview`
+ Update docs to have this dependency as well (config.js change)
+ Event logging still works as it did before. We can use the new angulartics directives for event tracking in the future, but our `miscService.pushGAEvent(a,b,c)` still works
+ Search term is now tacked on by the router for the search results page. Read `/docs/my-app/md/ga.md for details`.
+ `app-config.js` **Optional** updates : Added `APP_FLAGS. gaSearchParam`. Defaulted to q.
+ `/config.js` updates (for anyone overwriting this file):
```diff
@@ -12,6 +12,8 @@ define([], function() {
paths: {
'angular'       : "bower_components/angular/angular.min",
'angular-mocks' : "bower_components/angular-mocks/angular-mocks",
+        'angulartics'   : …
```
=> MUMUP-2139 : angulartics impl

uw-frame-components/css/buckyless/inner-nav.less
Goes with https://github.com/UW-Madison-DoIT/angularjs-portal/pull/389. 
Does anyone know when or why the border-bottom was changed from 3px to 4px? I think it should be 3px but I'm not sure if this breaks something someone else did.
Before (when hovering on 'MyUW'):
After:
=> Fix hover state of inner nav

uw-frame-components/css/buckyless/buttons.less
Flat buttons had the hover animation, which doesn't really make them flat. This fixes that
=> Fix button hover animation for flat buttons

uw-frame-components/css/buckyless/general.less
Small tweak to move the `.page-content` div down a smidge. Helps to align it with the bottom of the red nav bar.
=> css to go with marketplace search change

uw-frame-components/css/buckyless/base.less
Hover for an anchor in a paragraph for a `.btn` was doing funky things. This fixes that.
=> Fix anchor tags with btn classes

Gruntfile.js, package.json
Adds in `grunt serve` command which will :
+ build static
+ Run superstatic
+ Watch for any changes in `uw-frame-components`
You can also do:
+ `grunt run:get_bower` : just downloads bower components to reduce rebuild time
+ `grunt run:build_static` : Just builds static, nothing more, nothing less
+ `grunt run:run_static` : Builds and runs superstatic
+ `grunt watch` : Watches the uw-frame-components directory and triggers a `run:build_static`
=> Add in grunt serve command

Dockerfile
There was an issue where if you tried to do a bower install it would fail because git wasn't around (wat, yeah i don't know).
=> Fix issue with bower install

uw-frame-components/js/app-config.js, uw-frame-components/portal/main.js, uw-frame-components/static.html
+ If the silent login fails, it reports the failure, but continues with the loading experience. The app should handle the error not in the init block.
+ If the group service call fails it warns and switches to the default theme
+ If the require module fails to load it replaces the loading splash with error content:
=> MUMUP-2401 : Improve failed state

docs/markdown/configuration.md, uw-frame-components/portal/main.js
Before we looped through every single element to replace maybe a handful, that seemed silly.  Now it just loops over the keys in the override.js constant and replaces the value of that key in the config.js.  This also adds the ability to add new key/value pars to existing constants, like `APP_FLAGS`. Something we do pretty often in `angularjs-portal`. This may increase speed of the loading screen a bit, depending on your override.js file.
=> Make it so override.js can add new elements

Gruntfile.js, docs/markdown/home.md, docs/markdown/quickstart.md, docs/markdown/theming.md
+ Add in `grunt serve_docs` which does the same thing as `grunt serve` except it builds/serves docs
+ Add in documentation about theming
+ Reordered the home page a bit to hopefully make more sense
+ Documented the different ways to build a frame app, may be helpful for RF meetup
=> Document all the things

uw-frame-components/css/buckyless/general.less
Since the white-page is mimicking a bootstrap column,
it needs to float so it can grow to the size of its children
vertically.
=> White page mimic column

uw-frame-components/portal/features/controllers.js
The $rootScope is not needed. It was removed from the param list, but not the array. This has ill effects I won't give you the details on. This PR fixes the issue.
=> Fix dependency injection for features page

uw-frame-components/js/override.js, uw-frame-components/portal/notifications/partials/notifications-full.html
Change sort to be priority (true first), then id desc.
_Also minor cleanup, features shouldn't be overwritten by default :)_
=> MUMUP-2482 make priority a priority

uw-frame-components/portal/features/controllers.js
There was an odd edge case where a npe was getting thrown in the console if you don't have a cached theme. This fixes that.
=> Default state of mascot image doesn't throw a npe anymore

docs/markdown/theming.md
Adds clarification to crest size stating that image height will be scaled to 52 px.
=> Adds crest image size clarification

uw-frame-components/bower.json, uw-frame-components/config.js
Since https://github.com/angulartics/angulartics-google-analytics/releases/tag/0.2.0 was tagged, we can now move forward with this.
=> MUMUP-2396 : upgrade ga plugin for angulartics so we get rid of the ga issue

uw-frame-components/js/frame-config.js, uw-frame-components/portal/main.js, uw-frame-components/portal/main/controllers.js, uw-frame-components/portal/main/partials/body.html, uw-frame-components/portal/settings/partials/setting-option.html, uw-frame-components/portal/settings/partials/settings.html
+ Modifies the `THEME` structure to have an optional `materialTheme` with 3 children objects `primary`, `accent` and `warn`. These will then correlate to a theme in material during theme selection. Important thing. If the `materialTheme` is not defined, we still define a theme, but use the default pallettes.
+ Modifies the beta settings page to use `md-card`, `md-switch`, and `md-button`
+ We could define a default pallette that all schools have
+ The material implementation = many `style` tags in the head section. 16 per theme. Read more [here](https://material.angularjs.org/latest/Theming/05_under_the_hood)
=> Material theme to frame theme

docs/index.html, uw-frame-components/head-static.html, uw-frame-java/src/main/webapp/frame.jsp, uw-frame-static/index.html
+ Java `frame.jsp` was missing `angular-material.css`. Turns out that angular material doesn't look the best without CSS. 
+ Abstracted static head stuff that is downstream agnostic. 
+ `jsp:include` tag added to frame.jsp
+ `grunt includes added to index.html for both docs and static
=> Abstract static head information

uw-frame-components/css/buckyless/header.less, uw-frame-components/css/buckyless/notifications.less
before
after
also adjusted the priority notification lighten to be 10% instead of 20%.
=> Fix hardcoded colors for the notification bell

package.json, uw-frame-components/config.js, uw-frame-components/portal/main.js, uw-frame-components/portal/settings/controllers.js
+ Change initial config to do lazy loading during config
+ Update run config in main.js (loading phase) to generate the theme
+ Update beta-settings to generate the theme
Result : `jQuery('style[md-theme-style]').length` now returns 16 instead of 256
Tested with mac on safari (the reporting browser) and had a noticeable difference in load time (for the better)
=> MUMUP-2617: Material theme performance fix

uw-frame-components/js/frame-config.js, uw-frame-components/portal/features/controllers.js, uw-frame-components/portal/features/partials/announcement.html, uw-frame-components/portal/features/partials/features-modal-template.html, uw-frame-components/portal/features/services.js, uw-frame-components/portal/main/controllers.js, uw-frame-components/portal/settings/controllers.js, uw-frame-components/portal/settings/partials/user-settings.html
Allows dismissal of popups and announcements individually rather than dismissing one and then all earlier ones are dismissed with it.
Handles legacy conversion.
Allows multiple popups as well.
Little video in action:
We really haven't been writing test cases for a lot of our stuff.  I'm going to try to learn about how we do test cases and write up some documentation on it.
=> MUMUP-2605 Refactor mascot and popup announcement

uw-frame-components/css/buckyless/general.less, uw-frame-components/portal/misc/partials/loading-gif.html
Eventually we will probably get rid of this directive, but for now lets just do the loading circle that comes with angular material.
=> Change loading gif to the forever load circle.

Gruntfile.js, package.json, uw-frame-components/.gitignore, uw-frame-components/config.js, uw-frame-components/test/build.sh, uw-frame-java/pom.xml
So that Google analytics doesn't get blocked. Turns out the folder name is getting filtered as well.
=> During build move ga javascript to target/vendor for static and java

uw-frame-static/build.sh
Adds build changes from #258 to static's build.sh file so that `npm run static` no longer results in a 404 error when it looks for vendor/angulartics.ga.
=> Copy ga javascript into /vendor during static build

uw-frame-components/css/buckyless/base.less, uw-frame-components/css/buckyless/directives/app-header.less, uw-frame-components/css/buckyless/features.less, uw-frame-components/css/buckyless/footer.less, uw-frame-components/css/buckyless/frame.less, uw-frame-components/css/buckyless/general.less, uw-frame-components/css/buckyless/header.less, uw-frame-components/css/buckyless/notifications.less, uw-frame-components/css/buckyless/search.less, uw-frame-components/css/buckyless/widget.less, uw-frame-components/css/themes/common-variables.less, uw-frame-components/css/themes/uw-madison-variables.less, uw-frame-components/js/override.js, uw-frame-components/portal/features/partials/announcement.html, uw-frame-components/portal/main/partials/body.html, uw-frame-components/portal/main/partials/example-page.html, uw-frame-components/portal/main/partials/footer.html, uw-frame-components/portal/main/partials/header.html, uw-frame-components/portal/main/partials/username.html, uw-frame-components/portal/misc/partials/add-to-home.html, uw-frame-components/portal/misc/partials/app-header.html, uw-frame-components/portal/misc/partials/circle-button.html, uw-frame-components/portal/notifications/partials/notification-bell.html, uw-frame-components/portal/search/partials/search.html, uw-frame-components/staticFeeds/features.json
Hunker down cuz this one is a whopper...
- `header.html` and `app-header.html` each received a total overhaul and are now built with angular material
- `notification-bell.html`, `username.html`, and a number of other partials were also heavily modified to suit the new style
- Stripped out bootstrap popovers in favor of material menus
- Changed uw-madison theme's primary color to #c5050c and link color to #0479a8 (in accordance with wisc.edu)
- Added link hover transitions for smoother color changes
- Slimmed down mobile display by moving search bar into the main menu
- Several LESS files slimmed down/modified/reorganized
- Made some changes to the example page, mainly to experiment with a newer feature in Angular Material [(grid …
=> Materialize uw-frame's top bar and notifications

docs/markdown/directives.md, uw-frame-components/css/buckyless/directives/app-header.less, uw-frame-components/portal/main/partials/example-page.html, uw-frame-components/portal/misc/directives.js, uw-frame-components/portal/misc/partials/app-header.html, uw-frame-components/portal/misc/partials/frame-page.html
In this PR:
- Added params to app-header and frame-page that will allow displaying a single option button (without hiding it inside a dropdown menu) when true
**Notes:**
- This will enable displaying the compact/expanded toggle in the app header in angularjs-portal
- This change shouldn't affect any existing frame apps -- you have to know about the parameter to use it
- Small screens unaffected (will display dropdown menu with gear icon regardless of whether single-option flag is true or false)
- I'm not super excited about going this route, and I view it as a short-term solution. We should still revisit how we're delivering options menus
- I tried out @timlevett's suggestion of using a JSON list of links, which we could then format and display however we want, rather than the current …
=> Add option for single menu items in app-header

uw-frame-components/portal/misc/partials/app-header.html
Slightly increases the width of the app-header options menu to avoid horizontal scrolling when larger/longer options exist in the menu.
=> Increase width of options menu

uw-frame-components/portal/misc/partials/app-header.html
I suspect (but don't know) that this icon ought to be `aria-hidden` because for screen reader purposes it's decoration redundant with `{{::title}}`.
=> aria-hide the app-header app-title decoration icon.

uw-frame-components/js/override.js, uw-frame-components/my-app/main.js, uw-frame-components/portal/main/partials/example-page.html, uw-frame-components/portal/main/partials/file-not-found.html, uw-frame-components/portal/main/routes.js
+ Resolves #86 by creating a default 404 (file not found) page
+ Remove `override.js` entry to enable features by default. Assuming that was a mistake.
=> Add in 404 page, disabled features enabled by default

docs/markdown/injecting-dependencies.md
With suggestion from @nblair added in some other ways to run bower install during the build process of the downstream application.
=> Add in ways to run bower install via pom.xml or build.sh

uw-frame-components/portal/misc/partials/add-to-home.html
My last PR introduced a bug that caused the app-header options menu in mobile to open in a different position if it was repeatedly opened and closed. This PR fixes that bug.
=> Fix options menu bug

uw-frame-components/portal/main.js
Fix a bug where if you get punted to the default theme (system) the whole loading process breaks due to a `isArray` failure.
You can see this right now on `my-test.wisconsin.edu/web` if you are a Madison user.
=> THEMES.themes instead of THEMES

uw-frame-components/css/buckyless/features.less, uw-frame-components/js/override.js, uw-frame-components/portal/features/controllers.js, uw-frame-components/portal/features/partials/announcement.html, uw-frame-components/portal/misc/partials/app-header.html
This is the first pass at improving the UX of mascot announcements. There is more to be done after this!
- Mascot no longer shows announcements automatically on hover
- Instead, it moves slightly and shows a tooltip ("click to see what's new")
- Announcements only shown upon clicking the mascot
- Increase space given to app-header text on mobile screens
=> Improve mascot announcements UX

uw-frame-components/css/buckyless/general.less, uw-frame-components/css/buckyless/header.less, uw-frame-components/portal/misc/partials/add-to-home.html
+ Weird edge case where firefox doesn't work well if there is a button with an anchor tag inside of it.
+ Also cleaned up the `:not('.btn'), :not('.md-button')` (two different selectors) vs. `:not('.btn'):not('.md-button')` (one selector saying if its in either). I learned that [here](https://css-tricks.com/almanac/selectors/n/not/)
=> Cleanup add more to home for ff not handling <a> inside a <button> well

uw-frame-components/css/buckyless/header.less, uw-frame-components/css/buckyless/md-generated.less, uw-frame-components/css/buckyless/responsive.less, uw-frame-components/css/buckyless/widget.less, uw-frame-components/portal/features/partials/announcement.html, uw-frame-components/portal/main/partials/header.html, uw-frame-components/portal/main/partials/username.html
This PR works in tandem with [angularportal-js PR #514](https://github.com/UW-Madison-DoIT/angularjs-portal/pull/514). 
**Other changes in this PR:**
- Adjusted md-menu items and CSS so that md-menu content is in sentence-case
- Adjusted header so that crest images are hidden on xs/sm screens (to avoid overlapping search bar)
- *Note: The alternative to this would be enforcing a more rigid limit on the width of crest images for all themes (nothing bigger than 112x122, displayed at 56x56)*
=> Adjust spacing of widget input-groups to better utilize limited space

uw-frame-components/css/buckyless/general.less, uw-frame-components/css/buckyless/notifications.less, uw-frame-components/js/frame-config.js, uw-frame-components/js/override.js, uw-frame-components/portal/notifications/partials/notification-bell.html, uw-frame-components/staticFeeds/notifications.json, uw-frame-components/staticFeeds/sample_notifications.json
- Included Doug's work from the [MUMUP-2678 branch](https://github.com/UW-Madison-DoIT/uw-frame/tree/MUMUP-2678)
- Added `actionButtons` attribute to sample notifications
- `actionButtons` contains objects with the following attributes: `url`, `label`, `action`
- Added angular material attributes to ensure buttons appear in a row
- Added some CSS to reduce button size
- Changed background of priority notifications to generic light gray (previously we were lightening the theme's "color1," which was not always going to look good with white text)
- First button will be theme's primary color, last button will be the accent color
- Added black border around priority notifications to help set them apart from the rest of frame
- Added zero padding-left on `<ul>` lists to ensure …
=> Adjust appearance of priority notifications with buttons

uw-frame-components/css/buckyless/header.less
Fix for [MUMUP-2703](https://jira.doit.wisc.edu/jira/browse/MUMUP-2703). Just needed to concretely set the position of the top bar so it's not displaced when a new `fixed` element appears (the menu).
Resolves #289
=> Fix disappearing-header bug

uw-frame-components/js/app-config.js, uw-frame-components/portal/main/controllers.js
By default it'll just display MyUW, unless the frame app sets the NAMES.app_name, then it'll be the app name | frame name. Most frame names are MyUW. Additionally if the frame name is changed from MyUW the display will be frame name | app name (which will be MyUW by default). Unless its /web, then it'll always be MyUW.
Closes #214
=> Title is now NAMES.app_name | FRAME.title

uw-frame-components/css/buckyless/notifications.less
Noticed during sprint review that links in priority notifications are black. Added some CSS to allow them to use the given theme's `link-color`.
=> Add link color to priority notifications

uw-frame-components/js/frame-config.js, uw-frame-components/portal/features/services.js
Beta settings when checked will turn off group filtering on features.  Will allow user to get popups, mascot announcements, and see the features in the features page.
=> MUMUP-2717 Beta Feature to show all Announcements

uw-frame-components/css/buckyless/general.less, uw-frame-components/css/buckyless/widget.less
This PR goes hand-in-hand with [angularjs-portal #517](https://github.com/UW-Madison-DoIT/angularjs-portal/pull/517) and [myuw-overlays/entities #270](https://git.doit.wisc.edu/myuw-overlay/entities/merge_requests/270). The only reason changes to frame are included is because some of the CSS related to widgets already lived there. 
I've tried to separate the responsibilities a bit such that frame's widget-related CSS has to do with general styles (i.e. outer container attributes), whereas portal's widget-related CSS has to do with specific widget types that only exist in portal (i.e. list-of-links, weather, etc.). 
**More info and screenshots in [angularjs-portal #517](https://github.com/UW-Madison-DoIT/angularjs-portal/pull/517)**.
=> Improve consistency of widget appearance (uw-frame)

uw-frame-components/css/angular.less, uw-frame-components/css/buckyless/buttons.less, uw-frame-components/css/buckyless/md-generated.less, uw-frame-components/portal/settings/partials/user-settings.html
In this PR: 
- Override angular material's default styling to allow for sentence case buttons: 
- Make sure content in menus (buttons, links, switches, etc.) is consistently colored (had to use !important flag for now :/)
- Adjust user-settings page for sentence case buttons and to prevent button text from being clipped on mobile
=> Remove text-transform from material buttons

docs/markdown/directives.md, uw-frame-components/portal/misc/directives.js, uw-frame-components/portal/misc/partials/launch-button.html
Makes `<launch-button>` available for portal widget entities so we can provide a standard experience across widgets. Satisfies [MUMUP-2724](https://jira.doit.wisc.edu/jira/browse/MUMUP-2724)
- Added launch button directive and template
- Updated docs to describe the directive
=> Create launch button directive

uw-frame-components/css/buckyless/buttons.less, uw-frame-components/css/buckyless/directives/app-header.less, uw-frame-components/css/buckyless/features.less, uw-frame-components/css/buckyless/general.less, uw-frame-components/css/buckyless/header.less, uw-frame-components/css/buckyless/inner-nav.less, uw-frame-components/css/buckyless/notifications.less, uw-frame-components/css/buckyless/widget.less, uw-frame-components/css/themes/common-variables.less
This PR satisfies the requirements of [MUMUP-2688](https://jira.doit.wisc.edu/jira/browse/MUMUP-2688)
- All links that are styled like buttons will have no underline when hovered
- All regular links will have underline when hovered
- Mascot image no longer shows a different background color when hovered (that was an unintended effect of making it a md-button)
- Removed a lot of unused .less variables 
- Commented some .less files for clarification of their content
- Fixed some typos
- BONUS: Removed some hard-coded colors from the notifications page
=> Standardize link styles throughout frame

uw-frame-components/css/angular.less, uw-frame-components/css/buckyless/md-icons.less, uw-frame-components/head-static.html, uw-frame-components/portal/main/partials/example-page.html
+ added icon include to `head-static.html`
+ Added basic sizing per documentation recommendation.
+ Styled the example page with said icons
=> MUMUP-2739 : Add in material icons and some size classes

uw-frame-components/css/buckyless/notifications.less, uw-frame-components/css/themes/common-variables.less, uw-frame-components/js/override.js, uw-frame-components/portal/notifications/controllers.js, uw-frame-components/portal/notifications/partials/notifications-full.html, uw-frame-components/portal/notifications/services.js
- Replaced bootstrap elements with angular material components where appropriate
- Removed bootstrap tooltips
- Removed hard-coded colors
**Note:** You will notice in the gif that there's a bit of a delay when dismissing/restoring notifications. I think this could be resolved during a refactor that would include adding a "isDismissed" flag to the notification object itself. I backlogged [MUMUP-2740](https://jira.doit.wisc.edu/jira/browse/MUMUP-2740) to record that work.
=> Materialize notifications page

uw-frame-components/css/buckyless/features.less, uw-frame-components/css/buckyless/md-generated.less, uw-frame-components/css/themes/common-variables.less, uw-frame-components/js/override.js, uw-frame-components/portal/features/controllers.js, uw-frame-components/portal/features/partials/announcement.html, uw-frame-components/portal/features/partials/features.html, uw-frame-components/portal/main/partials/example-page.html
- Replaced bootstrap popover with angular material menu for mascot announcements
- Made the appearance of mascot menu a little more pleasant
- Updated appearance of features page
- Mascot now behaves as you'd expect -- he pops up a little on hover, goes back when the mouse leaves, fully appears on click, goes back when you click away
- Got rid of the superfluous "tell me more" link
- Made the "dismiss" link an icon button
- Fixed some "announcment" typos in code
- Did I mention you no longer have to click Bucky to make him go away???  👏👏👏👏👏👏👏
**Note:** The speech bubble effect has gone away. It turns out that angular material doesn't allow that kind of granular control over the positioning of menus. Personally, I think it looks better without it.
=> Makeover for mascot announcements

uw-frame-components/css/buckyless/general.less, uw-frame-components/css/buckyless/notifications.less
Previously, the `.md-tabs` and `.badge` tweaks were only applied to the notifications page. This change is necessary for the [new search page](https://github.com/UW-Madison-DoIT/angularjs-portal/pull/533) to appear correctly.
=> Make tab and badge styling global

uw-frame-components/css/buckyless/md-generated.less
Why should a good mascot image go to waste?
- Hacked some CSS to make the mascot fully visible when the mascot menu is open.
=> Make mascot visible when menu is open

uw-frame-components/css/buckyless/notifications.less, uw-frame-components/portal/notifications/controllers.js, uw-frame-components/portal/notifications/directives.js, uw-frame-components/portal/notifications/partials/notifications-full.html, uw-frame-components/portal/notifications/partials/notifications-list-item.html
For [MUMUP-2741](https://jira.doit.wisc.edu/jira/browse/MUMUP-2741)
- Moved the repeated code for notification items into a directive -- opted to go with the simplest version possible...not sure if it's worthwhile/helpful to move the buttons and "no notifications" cases into the directive
- Fixed some nit-picky syntax inconsistencies in the controller
=> Move notification items into directive

uw-frame-components/css/buckyless/header.less, uw-frame-components/css/buckyless/notifications.less, uw-frame-components/portal/main/partials/body.html, uw-frame-components/portal/main/partials/header.html, uw-frame-components/portal/misc/partials/frame-page.html, uw-frame-components/portal/notifications/controllers.js, uw-frame-components/portal/notifications/partials/notification-bell.html, uw-frame-components/portal/notifications/partials/notifications-full.html, uw-frame-components/portal/notifications/services.js, uw-frame-components/staticFeeds/sample_notifications.json
- Moved most of the logic handling notifications and their storage into the notifications service
- Added a service method that sorts notifications into dismissed/notDismissed arrays to be consumed by the controller, so the controller only has to worry about its two scope arrays
- Got rid of the "No [new/dismissed] notifications" message. Now, when there are no notifications of a type, that type's tab will simply disappear (similar to how the [outages site](http://outages.doit.wisc.edu/date/2016-09-23) doesn't show the "Unplanned" tab if there are no unplanned outages to show)
- Renamed some functions and variables to hopefully make their purposes more apparent to virgin eyes
- Added so many [jsdoc](http://usejsdoc.org/)-style comments to the service and controller that …
=> Refactor notifications

uw-frame-components/css/buckyless/widget.less
Noticed in predev that the catch-all link styles in frame were not in fact catching all.
=> Fix launch-button text-decoration

uw-frame-components/portal/features/controllers.js, uw-frame-components/portal/features/services.js
- Fixed the problem described in [MUMUP-2748](https://jira.doit.wisc.edu/jira/browse/MUMUP-2748)
- Minor format changes in `services.js` to make it a bit easier to read
=> Fix popup bug when displaying multiple popups

uw-frame-components/css/buckyless/md-generated.less, uw-frame-components/css/buckyless/widget.less, uw-frame-components/css/themes/common-variables.less
This PR goes hand in hand with [angularjs-portal pull #544](https://github.com/UW-Madison-DoIT/angularjs-portal/pull/544)
- Added some CSS that used to be in portal but should be here instead
- Added CSS to style widget action tooltips that have replaced bootstrap popovers
=> Add styles for widget action tooltips

docs/markdown/versions.md
Updates `versions.md` to link the just-published docs for the just-released uw-frame v2.9.0.
=> Link docs v2.9.0.

docs/markdown/configuration.md, uw-frame-components/portal/main.js
Resolves #333
You can now have a name as `APP_FLAG.defaultTheme`. Before you could just have an index number or the string `'group'`.
=> MUMUP-2761 : add ability to have a name for the default theme

.travis.yml, package.json, tools/uw-frame-static/build.js
- Made the `lessc` process more robust by adding postcss/autoprefixer to the build
- Added some dev dependencies required by node to read/write files
*Notes:* 
- *When running `npm run static:dev`, the `rm -rf` on uw-frame-static/target fails. This was an existing problem and is not a consequence of this PR. Fixing it is outside the scope of [MUMMNG-2853](https://jira.doit.wisc.edu/jira/browse/MUMMNG-2853)*
=> Add postcss/autoprefixer to uw-frame build

uw-frame-components/my-app/main.js, uw-frame-components/portal/main.js, uw-frame-components/portal/main/partials/access-denied.html, uw-frame-components/portal/main/partials/file-not-found.html, uw-frame-components/portal/main/partials/server-error.html, uw-frame-components/portal/main/partials/sorry-safari.html, uw-frame-components/portal/main/routes.js
Satisfies requirements of [MUMUP-2770](https://jira.doit.wisc.edu/jira/browse/MUMUP-2770)
- If `localStorage.setItem` trips an error, the user is redirected to `/sorry-safari`, where they will see an error message explaining the error and directing them to turn off private browsing or try a different browser.
- Minor design update to all error pages 
- Replaced FontAwesome icons with material icons in all error pages
=> Handle Safari private browsing error

tools/uw-frame-static/build.js
On an initial clone of the repo, the rm would fail (even though it has a -r).  Removes this line as someone could run `npm run clean` if they wanted to do a clean build.
=> Removes the rm that caused inital build failures

uw-frame-components/config.js
The angular-ui-bootstrap upgrade moves up 2 major versions and does
break compatibility with some older components. In particular
typeahead needed to switch the typeahead attribute to uib-typeahead.
=> Upgrade angular-ui-bootstrap and angular libraries

uw-frame-components/css/buckyless/directives/circle-button.less
[MUMMNG-2986](https://jira.doit.wisc.edu/jira/browse/MUMMNG-2986): Just added a min-height to circle-buttons to ensure they don't warp when there are two lines of text
=> Ensure circle buttons maintain shape

.editorconfig
> EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems. -- http://editorconfig.org/
This one says "files in this project should be utf-8 encoded, with two spaces per indent level, and no trailing whitespace except a line feed character at the end of each line."
IntelliJ and Eclipse detect these settings out of the box; vim needs a plugin.
=> Document whitespace convention

uw-frame-components/config.js, uw-frame-components/portal/main.js, uw-frame-components/portal/main/partials/header.html, uw-frame-components/portal/misc/services.js, uw-frame-components/portal/notifications/controllers.js, uw-frame-components/portal/notifications/partials/notification-bell.html
After much digging into things I still barely understand a even more trial and error, I believe I have a fix for [MUMUP-2804](https://jira.doit.wisc.edu/jira/browse/MUMUP-2804). 
[Predev](https://predev.my.wisc.edu) is still pointing at this branch, if you want to test it for yourself -- just be aware there is moderate delay between your searches/clicks and their appearance in the analytics interface.
- Removed the try/catch block that was added to `portal/main.js` in [this PR](https://github.com/UW-Madison-DoIT/uw-frame/pull/324/files) -- this seems to have righted the ship, but I only have a vague idea why
- Added event tracking to notification links in mobile menu and top bar (bell link)
- Adjusted mobile menu events to capture "Mobile Menu" category instead of …
=> Fix analytics not working

README.md, dependencyci.yml
Adds reassuring dependencyci.com badge as documentation of and link to the continual dependency checking.
Excludes `jstl:jstl` from license checking because the metadata on that dependency is screwy (it's an old reference implementation of a JSR spec), but not screwy in a way that adds risk to `uw-frame`, what with it being the same screwy that afflicts all the other [10,000 repositories that depend upon it](https://libraries.io/maven/jstl:jstl).
=> Add dependencyci badge

docs/Google-analytics.md, docs/announcements.md, docs/configuration.md, docs/directives.md, docs/overview.md, docs/quickstart.md, docs/theming.md
A bunch of edits picking away at uw-frame docs.
+ Fix broken links
+ Fix styling of code blocks
+ Fix styling of lists
+ Normalize headings
+ Sharpen prose
+ Simplify
+ Clean up whitespace
The individual semantic commits say what they do.
=> Documentation fixes and edits

package.json
Removes [deprecated](https://docs.npmjs.com/files/package.json#license) licensing metadata in favor of the modern SPDX reference approach.
Resolves this warning that had been in the npm console:
```shell_session
$ npm install
npm WARN uw-frame@3.0.3 license should be a valid SPDX license expression
```
=> Modernize the license declaration in package.json .

tools/uw-frame-static/build.js, uw-frame-java/pom.xml
Adds font-awesome, normalize.less, and bootstrap to the npm build (haven't been there since our restructure).  Haven't noticed because in the restructure maven added them in, which then is used in our builds.
So, this adds them in, then in turns takes it out of specifically having to have maven put them in.
Going more towards the goal of the maven build will just be a copy of the npm build packaged into an artifact, possibly that packaging not even being in this repository.
=> MUMUP-2844 Adds Font-Awesome to static build

uw-frame-components/portal/main/partials/access-denied.html, uw-frame-components/portal/main/partials/beta-header.html, uw-frame-components/portal/main/partials/file-not-found.html, uw-frame-components/portal/main/partials/header.html, uw-frame-components/portal/main/partials/server-error.html, uw-frame-components/portal/main/partials/sorry-safari.html, uw-frame-components/portal/main/partials/username.html, uw-frame-components/static.html
- Replaced hard-coded references to MyUW with `{{portal.theme.title}}`
=> Remove hard-coded 'badgerisms' from user-facing content

uw-frame-components/portal/main/partials/access-denied.html, uw-frame-components/portal/main/partials/file-not-found.html, uw-frame-components/portal/main/partials/server-error.html, uw-frame-components/static.html
Reduces need to fork-and-customize HTML templates when configuring `MISC_URLS.helpdeskURL` to point elsewhere than DoIT Help Desk.
=> Not necessarily the DoIT Help Desk.

uw-frame-components/css/themes/uw-colleges-variables.less, uw-frame-components/css/themes/uw-extension-variables.less, uw-frame-components/css/themes/uw-greenbay-variables.less, uw-frame-components/css/themes/uw-lacrosse-variables.less, uw-frame-components/css/themes/uw-oshkosh-variables.less, uw-frame-components/css/themes/uw-parkside-variables.less, uw-frame-components/css/themes/uw-platteville-variables.less, uw-frame-components/css/themes/uw-stevens-point-variables.less, uw-frame-components/css/themes/uw-stout-variables.less, uw-frame-components/css/themes/uw-superior-variables.less, uw-frame-components/css/themes/uw-system-variables.less, uw-frame-components/css/themes/uw-whitewater-variables.less
- Lightened link colors that were too dark
- Darkened colors that were too light
- Changed link colors for Oshkosh and Superior to colors that can be found on their respective home pages
- All link colors meet WCAG AA contrast standards
*Note: I did not change the black link color for UW-Milwaukee. Looking at [uwm.edu](http://uwm.edu/), they use the color black without underline for all their links, so the current MyUW theme would be in keeping with their home page. I'd rather put the onus on someone from UWM to change it if they feel it's necessary.*
=> Adjust link colors for most themes

uw-frame-components/portal/notifications/services.js, uw-frame-components/portal/notifications/spec/notification_services_spec.js
Fixes a bug where the data object to find to show notification would return but we were checking if length > 0.  Well, length>0 is only valid when it's an array, so if it was just an object, it would fail and not show the notification.  Added test case as well.
----
=> MUMUP-2875 Fixes bug with dataObject in notification feed caused it to not display

uw-frame-components/portal/widgets/partials/type__list-of-links.html, uw-frame-components/portal/widgets/partials/type__option-link.html, uw-frame-components/portal/widgets/partials/type__rss.html, uw-frame-components/portal/widgets/partials/type__search-with-links.html, uw-frame-components/portal/widgets/partials/type__weather.html, uw-frame-components/portal/widgets/partials/widget-card.html
[MUMMNG-3247](https://jira.doit.wisc.edu/jira/browse/MUMMNG-3247)
- Check if a widget's configuration specifies a target attribute for its launch button, default to `_blank` if none is specified
- Ensure "basic" widget type leverages the same functionality for its larger clickable surface
=> Uniformly implement link target attribute from widget configuration

docs/notifications.md, uw-frame-components/portal/notifications/controllers.js, uw-frame-components/portal/notifications/services.js, uw-frame-components/portal/notifications/spec/notification_services_spec.js
What #386 did for `master` towards `4.0.0`, this would do for `3-maint` towards `3.2.0`.
Backports the filtered-based-on-runtime-data notifications feature to latest stable `uw-frame` to enable shipping this feature in a stable `angularjs-portal` release sooner than a frame-4.0.0-based AngularJS-portal will be available.  And particularly, in time for displaying the 2017 WRS Annual Statements of Benefits notification that 2016 statements are available, to only those users who actually have them available.
----
=> v3: MUMUP-2875 : Personally filtered notifications

uw-frame-components/portal/widgets/controllers.js
Adds array filtering that was removed in [angularjs-portal #612](https://github.com/UW-Madison-DoIT/angularjs-portal/pull/612).
The gratuitous logging is for testing purposes and should be removed before this goes to prod.
=> Restore filteredArray functionality

uw-frame-components/css/buckyless/widget.less, uw-frame-components/portal/widgets/controllers.js, uw-frame-components/portal/widgets/partials/widget-card.html
Fixes this:
Decisions about how wide widgets can/should be should be left up to the people implementing widgets. It's up to individual projects to define containing elements and layouts.
=> Remove constraints to widget width and leave it up to containing element

uw-frame-components/portal/widgets/controllers.js
Rationale for doing this is partly due to low ROI and also because it seems like poor practice to add functions to a generic controller `CustomWidgetController` that are used by only one widget. If a widget's data model needs that much finagling to get it right, it probably should be its own type.
=> Remove leave balances sorting function

docs/directives.md, uw-frame-components/portal/widgets/partials/type__list-of-links.html, uw-frame-components/portal/widgets/partials/type__option-link.html, uw-frame-components/portal/widgets/partials/type__rss.html, uw-frame-components/portal/widgets/partials/type__search-with-links.html, uw-frame-components/portal/widgets/partials/type__weather.html, uw-frame-components/portal/widgets/partials/widget-card.html
[MUMMNG-3294](https://jira.doit.wisc.edu/jira/browse/MUMMNG-3294)
- Changes the default behavior for widget launch buttons to open in same window/tab
=> Launch behavior should default to same tab

.travis.yml
Use default container build for faster build start time.
Install latest node js version using the node version manager.
Cache npm and maven dependencies to reduce wait time on network calls.
----
=> Test against multiple jdks, improve build time

.gitignore
Local `.ruby-version` can guide RVM in support of locally running Jekyll.
I keep accidentally trying to check my local `.ruby-version` into the shared repo. Marking it ignored should reduce this annoyance.
----
=> Ignore docs/.ruby-version

uw-frame-components/css/buckyless/general.less, uw-frame-components/css/buckyless/widget.less, uw-frame-components/portal/widgets/controllers.js, uw-frame-components/portal/widgets/partials/demo-widgets.html, uw-frame-components/portal/widgets/partials/type__rss.html
[MUMUP-2913](https://jira.doit.wisc.edu/jira/browse/MUMUP-2913)
- Add styles to stop RSS titles from wrapping
- Don't show dates if they're undefined (currently, the [rssToJson](https://github.com/UW-Madison-DoIT/rssToJson/blob/master/src/main/java/edu/wisc/my/rssToJson/service/RsstoJsonServiceImpl.java) doesn't set any pubDate, so it's always coming back undefined. Until it's fixed, titles should be displayed at full width 
- Do not underline titles on hover
- Adjust default limit of title length depending on whether dates are displayed
- Leverage launch-button directive within RSS widgets
- Trim leading/trailing spaces from RSS titles before truncating them
- Adjust appearance of widgets demo page in static
=> Fix RSS widget display wonkiness

uw-frame-components/portal/widgets/controllers.js, uw-frame-components/portal/widgets/partials/type__rss.html
Allowing widget creators the ability to specify a date format could create an inconsistent appearance. Sticking to a rigid format is the best way to ensure uniform appearance across all RSS widgets. 
Also in this PR:
- Don't let widget config set limits that are too long
=> Format dates consistently across all RSS widgets

committers.md
Bootstrap initial Committers so that these committers can bootstrap future Committers.
Firming up governance in working towards Incubation exit criteria.
----
=> Formally bootstrap initial Committers

README.md, docs/releasing.md
This is the `uw-frame` version of https://github.com/UW-Madison-DoIT/angularjs-portal/pull/625 .
+ Notes that since we've adopted Apache rules and have a formalized committer roster now, Committers should authorize the release or delegate this authority to a release engineer or so.
+ Starts to reflect the `uPortal-app-framework` and `uPortal-home` naming
----
=> Reminder to release under Apache rules

uw-frame-components/css/buckyless/header.less
It shouldn't underline on hover
=> Add higher specificity to header link

uw-frame-components/css/buckyless/widget.less, uw-frame-components/portal/widgets/directives.js, uw-frame-components/portal/widgets/partials/compact-widget-card.html
Moves more widget code from uPortal-home to the uPortal-App-Framework, so everyone can enjoy a good compact mode widget.
Fixes a bug in uPortal-home where compact mode wasn't rendering because of switching to the new layout call in portal
----
=> Compact widget directive

uw-frame-components/css/buckyless/widget.less, uw-frame-components/portal/widgets/services.js
#419 added the ability to show an error message when a user requests a widget they don't have permission to use/see. This PR just leverages some existing functionality (maintenance mode) to display the error in a similarly attractive way.
=> Beautify permission-denied widget error

tools/uw-frame-static/build.js
changes to frame weren't showing up when I ran static:dev, so I went through and fixed the build script.  
Standardized error throwing, copy now overwrites.
----
=> cleaning up filesystem errors on build-static

uw-frame-components/css/buckyless/header.less, uw-frame-components/css/buckyless/notifications.less, uw-frame-components/css/buckyless/widget.less
Continuation of #422 -- Adjusts depths of some other elements to avoid conflicts.
Ex. Turn this:
Into this:
=> Further improve depth of elements

uw-frame-components/css/buckyless/directives/app-header.less, uw-frame-components/css/buckyless/notifications.less, uw-frame-components/portal/main/partials/header.html, uw-frame-components/portal/misc/partials/app-header.html, uw-frame-components/portal/notifications/partials/notification-bell.html, uw-frame-components/portal/notifications/services.js, uw-frame-components/portal/search/partials/search.html
I got a little carried away while working on #425. This PR replaces most of the font awesome icons in the top bar and app header with material ones.
=> Replace most fa-icons with material

uw-frame-components/css/buckyless/header.less
=> Fix md-menu forcing scroll when priority notifications visible

uw-frame-components/js/app-config.js, uw-frame-components/portal/widgets/services.js
if we pull the '.json' suffix into configuration, we're able to do some creative stuff with the uri we call for widget data (like using a base64 data uri).
----
=> pulling string into configuration

uw-frame-components/portal/widgets/controllers.js
this would allow us to let the directive reload itself.  Not used here yet, but trying it out in widget-creator
----
=> making the widget init function accessible via scope

uw-frame-components/css/buckyless/md-generated.less, uw-frame-components/portal/main/partials/header.html, uw-frame-components/portal/main/partials/username.html, uw-frame-components/portal/notifications/partials/notification-bell.html, uw-frame-components/portal/search/partials/search.html
- Added tooltips to buttons that appear in the header/app bar (notifications, username menu, search, etc.) with half-second delay.
- Darkened background for widget info tooltips
----
=> Add tooltips to header buttons a la Google apps

uw-frame-components/portal/features/services.js
Fixes a bug when the code updates legacy dismissed announcement id storage to the new format.  Bug introduced about a month ago where if there is not any legacy dismissal ids, a chain reaction of rejection causes no announcements of any type to show.  This pr also adds some return type documentation, but doesn't add unit tests to prevent this in the future.
Marked WIP because of the failing lint test that https://github.com/UW-Madison-DoIT/uw-frame/pull/449 takes care of.  When that is merged, I'll rebase, then this should be good to go and will pass the CI
----
=> Announcement bug fix

tools/uw-frame-static/build.js, uw-frame-components/css/themes/default-variables.less, uw-frame-components/css/themes/default.less, uw-frame-components/js/frame-config.js, uw-frame-components/portal/widgets/controllers.js, uw-frame-components/portal/widgets/partials/widget-icon.html, uw-frame-java/pom.xml
Getting frame to work with uPortal master.  This should take care of most of the big things.
* Adds a default theme to go with uPortal
* Fixes a bug with launch urls that UW-Madison never sees because of our explicit handling of urls in portlet definition files.
* Fixes a bug where widget url wasn't working (again, never saw it because of our explicit handling of icons in portlet definition files).
----
=> Frame works withu portal master

docs/notifications.md, uw-frame-components/staticFeeds/notifications.json
Adds a sample notification exercise for adopters to try out.
----
=> Adds a notification user exercise

docs/announcements.md
Adds an exercise for adopters to try out features/announcements locally.
----
=> Adds a feature exercise

uw-frame-components/js/app-config.js
Reverts this change, so that default behavior won't change in the next release.
Heads up due to this [comment](https://github.com/UW-Madison-DoIT/uw-frame/pull/453/files/e3ab440dc4bdf6083108195eda045dcb7ab9f837#diff-de864f63fac068677f42dde719b42604R14)
Will need to think about default behaviors as a whole later on (soon)...
----
=> Reverts groups url back to previous default state

uw-frame-components/css/buckyless/md-generated.less, uw-frame-components/css/buckyless/notifications.less, uw-frame-components/portal/features/partials/announcement.html, uw-frame-components/portal/main/partials/header.html, uw-frame-components/portal/notifications/partials/notification-bell.html, uw-frame-components/portal/notifications/partials/notifications-full.html, uw-frame-components/portal/settings/controllers.js, uw-frame-components/portal/widgets/partials/demo-widgets.html, uw-frame-components/staticFeeds/sample_notifications.json
[MUMUP-2967](https://jira.doit.wisc.edu/jira/browse/MUMUP-2967): Change notification bell to show dialog. **Goal: Improve UX by allowing users to see notifications without having to navigate to a new page.**
- Notifications bell now shows a menu dialog (like mascot announcements) so notifications can be viewed and interacted with without needing to navigate to a new page
- Bell still shows if no new notifications, functions as a link to notifications page
- (*bonus!*) Switched "dismiss" button on notifications page to use material icon
- (*bonus!*) Fixed a bug where an unclosed quote was causing the notifications link to not appear in the mobile menu
- (*bonus!*) Fixed a bug where priority notification fixed banner wasn't visible on large screens
- (*bonus!*) Added a bit …
=> Notifications

uw-frame-components/css/buckyless/md-generated.less, uw-frame-components/portal/features/partials/announcement.html, uw-frame-components/portal/notifications/partials/notification-bell.html
- "See all" link in the notifications/announcements dialog now shows the number of things to view
- Small CSS changes to ensure new content fits without wrapping
----
=> Show number of notifications/announcements in see all link

.travis.yml
Enables testing uw-frame on macOS, in addition to the existing Linux and Windows platform testing.
----
=> Add macOS environment to Travis CI

committers.md
+ Documents that [Christian Murphy elected Committer](https://groups.google.com/a/apereo.org/d/msg/uportal-dev/qcl7cyVWCDU/Z_mUyIXBAQAJ).
+ Documents mechanics for adding a committer.
----
=> Add Christian Murphy as committer

uw-frame-components/portal/widgets/controllers.js
The weather widget will not put itself in an error state unless a network error occurs. This checks the data response for reported errors, and treats that as an error condition.
----
=> error checking weather data response

docs/README.md, docs/make-a-widget.md, docs/widget-launch-button.md, docs/widgets.md
Companion of [angularjs-portal#657](https://github.com/UW-Madison-DoIT/angularjs-portal/pull/657)
- Added widget creation and configuration docs that were formerly part of the angularjs-portal docs
- Updated links to widget creator tool
- Updated widget config documentation to use `mdIcon` instead of `faIcon`
----
=> Move widget documentation from angularjs-portal

docs/configuration.md, docs/theming.md, uw-frame-components/css/buckyless/header.less, uw-frame-components/css/buckyless/md-generated.less, uw-frame-components/js/app-config.js, uw-frame-components/js/frame-config.js, uw-frame-components/portal/main/controllers.js, uw-frame-components/portal/main/partials/header.html, uw-frame-components/portal/main/partials/username.html, uw-frame-components/portal/main/services.js, uw-frame-components/portal/settings/controllers.js, uw-frame-components/portal/timeout/controllers.js, uw-frame-components/portal/timeout/services.js, uw-frame-components/staticFeeds/Shibboleth.sso/Session.json
[MUMPFL-152](https://jira.doit.wisc.edu/jira/browse/MUMPFL-152): As a **MyUW Madison** user, I would like to be able to easily find out what my campus id number is, so that I don't have to hunt for it every time I need it.
- Get the `wiscEduStudentID` attribute (campus ID) from Shibboleth and display it if available
- Add app flag to configure whether campus ID should be displayed
- Get user `displayName` from Shibboleth session instead of /portal *(any possibility this could negatively impact non-UW users/developers?)*
- Update username menu to show these attributes and link to [my-profile](https://github.com/UW-Madison-DoIT/my-profile) app 
- Add theme config attribute "profileUrl" to set a URL for "profile" app/page
- Show username menu on mobile
- Document new feature …
=> Display campus ID in username menu

docs/make-a-widget.md, uw-frame-components/portal/widgets/controllers.js, uw-frame-components/staticFeeds/list-of-links-via-url.json, uw-frame-components/staticFeeds/sample-widget__list-of-links.json
This change adds functionality to the list-of-links widget type to retrieve the list from a URL rather than a hardcoded portlet preference. 
----
- [ x] This Contribution is under the terms of Individual [Contributor License Agreements][] (and also Corporate Contributor License Agreements to the extent applicable) appearing in the [Apereo CLA roster][].
=> Add URL capability to list of links type

docs/notifications.md
In the end, we currently require uPortal groups so the Manifest reference could be confusing. And it does not have meaning beyond UW-Madison.
----
=> Remove Manifest group reference

.travis.yml
1. Detect whether the current CI build is caused by Greenkeeper
2. Update the lockfile with the latest version of the updated dependency using the package manager’s built in mechanism
3. Push a commit with the updated lockfile back to the Greenkeeper branch
reference: https://github.com/greenkeeperio/greenkeeper-lockfile#how-does-it-work
----
=> fix(ci): Update Travis CI script so greenkeeper works with the lockfile

tools/uw-frame-static/build.js, uw-frame-components/css/buckyless/widget.less
[MUMUP-2977](https://jira.doit.wisc.edu/jira/browse/MUMUP-2977): "it covers up the session timeout modal"
- Reduced z-index of maintenance overlay so it no longer sits on top of modals or top bar
----
=> Lower z-index of maintenance mode overlay

uw-frame-components/portal/settings/services.js
So, finally getting around to testing https://github.com/UW-Madison-DoIT/uw-frame/pull/308 and it didn't work.  It wasn't sending the parameters as params, but rather data.  (https://docs.angularjs.org/api/ng/service/$http#post)  
My screen recorder is acting up, so no video.  I'll try to work on that.
----
=> MUMUP-2699 Adds ability for portal skin switching

LICENSE, NOTICE
Trying to follow Apache Software Foundation practices.
So, uPortal-application-framework has two third party things bundled in the source code (glyphicons and sortable.js), both via The MIT License. [Per ASF guidance](http://www.apache.org/dev/licensing-howto.html#permissive-deps), acknowledged these at the bottom of `LICENSE`. (It was news to me to prefer to do this in `LICENSE` rather than `NOTICE`).
uPortal-application-framework has lots of other dependencies, but doesn't bundle their bits, so need not acknowledge them formally in `NOTICE` or `LICENSE`.
In `NOTICE`, I don't actually understand why it would be correct to say it's "Copyright the Apereo Foundation" since the authors rather than the foundation retain actual copyright ownership -- contributors only license their …
=> Acknowledge bundled dependencies and add NOTICE file

docs/configuration.md, uw-frame-components/portal/main/controllers.js
Shibboleth isn't the best to use on the front-end now that we've masked the values.  Reverting back to using the portal session for user's name.
----
=> MUMUP-2990 Use portal session rather than Shibboleth

package-lock.json, package.json
Superstatic version 4.2 introduced a dependency on shrink-ray, which introduced a dependency on node-zopfli, which introduces the need for a c compiler when building.  We're using the mvn deploy command to push out new releases.  This calls a mvn exec command 'npm install'.  npm install still 'succeeded' before, but exited with a code 1 (definitions of succeed vary), causing the mvn deploy command to fail.
----
=> fix: Use only 4.1.x version of superstatic not 4.x

uw-frame-components/portal/main/partials/header.html, uw-frame-components/staticFeeds/sample-messages.json
[MUMUP-3005](https://jira.doit.wisc.edu/jira/browse/MUMUP-3005): "As a user dismissing a priority notification, I would like to not see a visual gap between the header and the top of the browser page, so that my confidence is not eroded by glitches."
- #484 introduced a bug where the top bar failed to adjust to dismissal of a priority notification
- Added more useful sample messages
----
=> Fix sticky priority notifications 

uw-frame-components/portal/messages/controllers.js, uw-frame-components/portal/messages/filters.js, uw-frame-components/portal/messages/services.js
#484 I introduced a bug where clicking the "restore" button on a notification (while on the /notifications page) didn't actually update the list of seen message IDs in storage. This is because I complete forgot to include this functionality /facepalm
- Dismissing and restoring notifications now correctly saves the result  
----
=> Fix dismiss/restore message state not persisting

uw-frame-components/css/buckyless/directives/username-menu.less, uw-frame-components/css/buckyless/features.less, uw-frame-components/css/buckyless/frame.less, uw-frame-components/css/buckyless/general.less, uw-frame-components/css/buckyless/header.less, uw-frame-components/css/buckyless/md-generated.less, uw-frame-components/css/buckyless/notifications.less, uw-frame-components/css/buckyless/widget.less, uw-frame-components/css/themes/common-variables.less, uw-frame-components/portal/main/controllers.js, uw-frame-components/portal/messages/partials/notifications-bell.html, uw-frame-components/portal/misc/partials/app-header.html, uw-frame-components/portal/misc/partials/frame-page.html, uw-frame-components/staticFeeds/sample-messages.json
[MUMUP-3006](https://jira.doit.wisc.edu/jira/browse/MUMUP-3006): "As a user, I'd like a smoother experience when dismissing priority notifications, so that I can see the action happening, rather than just a disappearing bar."
- Added animations for appearance/dismissal of priority notifications
- Adjusted design of priority notifications to be more attractive (hopefully)
- Made a little more room for options buttons in app-header
- Adjusted some z-indexes so not to overlay Angular Material modals
- Adjusted confusing CSS dealing with fixed-positioned elements
- Username in user menu no longer all caps, first letter capitalized instead
- Added LESS variables for 5 levels of depth (per material design)
- Renamed some LESS variables so not to tie them to specific HTML …
=> Animate priority notifications [nice-to-have] 

uw-frame-components/staticFeeds/Shibboleth.sso/Session.json
changing the mock data to use an 8 hour expiration, like the real thing.
----
=> upping the expiration on the mock session to be 8 hours

package.json, uw-frame-java/pom.xml
Next version will be 5.0.0 because not-backwards-compatible change to implement `messages.json` rather than `features.json` and `notifications.json` is pending release.
----
=> chore(versioning): 5.0.0-SNAPSHOT rather than 4.1.1-SNAPSHOT

uw-frame-components/css/buckyless/features.less, uw-frame-components/css/buckyless/md-generated.less, uw-frame-components/css/buckyless/notifications.less, uw-frame-components/portal/messages/controllers.js, uw-frame-components/portal/messages/partials/announcement-mascot.html, uw-frame-components/portal/messages/partials/announcement-popup-template.html, uw-frame-components/portal/messages/partials/notifications-bell.html, uw-frame-components/portal/messages/services.js, uw-frame-components/staticFeeds/sample-messages.json
[MUMUP-3008](https://jira.doit.wisc.edu/jira/browse/MUMUP-3008): "As a user I would like notification indicators to reflect reality quickly so that I do not get the wrong impression from their state prior to their data loading."
- Notifications bell now shows a loading spinner while retrieving notifications
- No more UI delay when dismissing notifications/announcements from menus
- Empty state for notifications menu
- Notifications menu, mascot menu, and announcement popup now properly implement the `actionButton` and `moreInfoButton`
- Priority notifications in menu now have some spacing between icon and message
----
[Contributor License Agreements]: …
=> Speed up notifications bell (and other improvements)

docs/releasing.md
I forgot to update JIRA last release, adding it to the documentation
----
=> docs: Add documentation about JIRA Releases

LICENSE
Apereo does not currently have an ICLA on file for @jiayinjx , an [already-acknowledged Contributor](https://github.com/UW-Madison-DoIT/uw-frame/blob/master/docs/contributors.md). Where included her contributions were intentionally Contributed, so at the least they can be licensed directly via [Apache2 clause 5](https://www.apache.org/licenses/LICENSE-2.0.html#contributions) regardless of ICLA status.
That is, in effect, bundle @jiayinjx 's Contributions as an Apache2-licensed bundled dependency. [Apache documentation suggests we don't actually have to do anything at all](http://www.apache.org/dev/licensing-howto.html#alv2-dep) in `LICENSE` to do this.
A closer audit might reveal that none of Liu's Contributions remain in the current product. While valued, the original Contributions were …
=> fix(license): acknowledge Liu contributions via Apache 2 clause 5.

CHANGELOG.md
:information_source: About Keep a Changelog
This takes a different approach to keeping a changelog.
Rather than a primarily automated process based off commit messages. :robot: 
This takes the purely human approach of letting the release manager add a description of changes. :memo: 
While still offering some recommendations on how to structure the changelog.
:link: from [Keep a Changelog docs](http://keepachangelog.com/en/1.0.0/)
*  Changelogs are *for humans*, not machines.
* There should be an entry for every single version.
* The same types of changes should be grouped.
*  Versions and sections should be linkable.
*  The latest version comes first.
* The release date of each versions is displayed.
* Mention whether you follow [Semantic Versioning](http://semver.org/).
* `Added`  for …
=> docs(changelog): add changelog for version 5.1.0 to 3.0.0

uw-frame-java/pom.xml
this avoids  conflict between the conventional commit linter and the maven release plugin
See https://github.com/UW-Madison-DoIT/angularjs-portal/issues/682
----
=> build(maven): configure maven release plugin commit prefix

uw-frame-components/portal/misc/filters.js, uw-frame-components/portal/widgets/partials/compact-widget-card.html, uw-frame-components/portal/widgets/partials/type__option-link.html
Using logic to set target rather than pulling from widget properties. It happens to be the dumbest logic, but still logic. https://tools.ietf.org/html/rfc3986#section-3
----
=> feat(widget): use smart target on option-link widget

docs/messaging-implementation.md, uw-frame-components/css/buckyless/md-generated.less, uw-frame-components/css/buckyless/notifications.less, uw-frame-components/portal/messages/filters.js, uw-frame-components/portal/messages/partials/announcement-mascot.html, uw-frame-components/portal/messages/partials/notifications-bell.html, uw-frame-components/portal/messages/partials/notifications-list-item.html, uw-frame-components/portal/messages/partials/view__notifications.html, uw-frame-components/staticFeeds/sample-messages.json
[MUMUP-3021](https://jira.doit.wisc.edu/jira/browse/MUMUP-3021): "As a user, I would like MyUW notifications to sometimes be non-dismissable, so that I am reminded more often and can't accidentally dismiss a notification that is attempting to notify me of a critical action I need to take."
- Add support for `notDismissible` attribute in messages data model
- Tweak notifications/announcements menu UI
- Priority flag less disruptive of UI, but still noticeable
- Announcement titles look like notification titles
- Description text slightly lighter color
- Dismiss button centered in announcement menu items
- If addToHome action has already been taken, disable button
- Update messaging configuration doc
----
[Apereo CLA roster]: …
=> Notifications may be non-dismissible

uw-frame-components/js/app-config.js, uw-frame-components/js/override.js
- Set the default path for `optionsTemplateURL` to null so there is no options template unless specified (avoid new projects using the example template in uw-frame static environment)
- Set example template path in override so static build still uses it
----
=> fix: Set default options menu to null

uw-frame-components/portal/messages/controllers.js, uw-frame-components/portal/messages/filters.js, uw-frame-components/portal/messages/partials/announcement-mascot.html
This functionality adds a widget to the homepage by clicking an action button in a feature announcement.
----
- [ X] This Contribution is under the terms of Individual [Contributor License Agreements][] (and also Corporate Contributor License Agreements to the extent applicable) appearing in the [Apereo CLA roster][].
=> MUMUP-2580 Add widget from mascot announcement

docs/assets/css/style.scss, uw-frame-java/pom.xml
Our github pages were looking funky:
vs, what it should look like
SCSS files used in jekyll have to start with a front matter comment and can't start with a header license.  This excludes scss files in the docs directory from having the license header added automatically and fixes the existing comment to move beneath the front matter comment.
----
=> fix(license): remove scss auto-license in /docs

.npmrc, package.json
@vertein created https://www.npmjs.com/org/uportal to house our projects in npm. Adding the scope to the build.
----
=> build: adding @uportal org scope, publishing publicly by default

components/css/buckyless/frame.less
=> fix(ui): Eliminate gap between top bar on mobile

components/portal/messages/partials/notifications-bell.html, components/staticFeeds/sample-messages.json
[MUMMNG-3880](https://jira.doit.wisc.edu/jira/browse/MUMMNG-3880): "As a target of a high priority notification, I want the buttons in the header display to work so that I can take the appropriate action."
- Fix a bug where buttons weren't properly binding to scope
No idea how this one managed to slip through :P
----
=> fix: Properly bind URLs in priority notifications

components/portal/messages/services.js
Fixes a fallthrough that returned the message anyway if the filter criteria failed.
----
=> fix: return nothing on filter fail

components/css/buckyless/notifications.less, components/portal/messages/partials/notifications-list-item.html, components/portal/messages/partials/view__notifications.html, components/portal/misc/partials/app-header.html
- Notification no longer clickable, but displays action but (same as bell menu)
- High priority indicator matches bell
- Fixed some layout/spacing wonkiness so it's more consistent on small and large screens
- Add analytics to dismissal from notifications page
- Fixed a typo in analytics message
- Adjust app-header spacing on small screens to leave more room for app-header-options
----
=> fix(ui): Update notifications page to match functionality of bell

components/css/buckyless/search.less, components/portal/main/controllers.js, components/portal/main/partials/header.html, components/portal/search/directives.js, components/portal/search/partials/search.html
[MUMUP-3099](https://jira.doit.wisc.edu/jira/browse/MUMUP-3099): "As a mobile user of MyUW, I'd like the search button to do something, so that I'm not confused when I click the button and nothing happens."
- Refactored behavior of search directive
- Redesigned appearance of mobile search field to take up less space
*To do: Animate open/close of mobile search*
----
=> fix: Redesign mobile search

components/js/frame-config.js
We had an issue with my.wisconsin.edu defaulting to the uPortal theme rather than uw-system. On top of that, search/marketplace is broken with the uPortal theme ( #559 ). We're not quite operationally ready for uPortal to be the default theme yet, so this changes it back to uw-system.
----
=> fix(theme): using uw-system as default theme

components/portal/misc/filters.js
Adding a filter to calculate whether `noopener noreferrer` should be added to an anchor based on the target value.
----
=> feat: adding filter to calculate rel on anchors

components/js/frame-config.js
got a little too zealous renaming the uPortal theme. We still need it to match a skin in uPortal for backend rendered portlets.
----
=> fix: portalSkinKey has to match a skin on backend uPortal

components/css/buckyless/search.less, components/css/themes/common-variables.less, components/portal/messages/controllers.js, components/portal/messages/partials/notifications-bell.html, components/portal/search/partials/search.html
[MUMMNG-2880](https://jira.doit.wisc.edu/jira/browse/MUMMNG-2880): "As a user dismissing/un-dismissing notifications on the notification page, I would like the bell icon to update to reflect my new unread count, so that consistency is maintained."
- Hide notification bell (and mobile menu count) when user is viewing the full notifications page
- Bonus: Animate mobile search bar open/close
Because the `notifications-bell` (in its many forms) and `view__notifications` templates both use `NotificationsController` to establish and manipulate scope, you would think the scope would be shared among all the things that use that controller. However, this is not the case. The scope of the full view is isolated from the scope(s) of the various instances of the directive. This means …
=> fix: Obscure notifications bell when on full view

components/portal/messages/controllers.js, components/portal/messages/services.js
After pointing star app at new messages feed, the service fails to get messages (a bigger problem than this PR addresses). When it fails, the angular controls hangs because the promise returns `undefined`. This PR just makes sure the block doesn't continue if the promise result is undefined.
----
=> fix: Fix app hang when promise returns undefined

components/portal/messages/controllers.js, components/portal/messages/partials/notifications-bell.html, components/portal/messages/services.js
- First checks if configured notifications url points to portal base path (`/web`), then evaluates `$location.path()`
- Fixed a bug where incorrect type check was causing notifications feed to always be empty
This is a little hacky, but the idea is if a frame app wants to point to the portal-wide notifications feed, it has to point to /web. Since /web is the portal base path (and not included in any $location getters), evaluating the path against the configured notificationsPageURL will always result in `false`. We have to check for /web, and it it's not part of the configured path, we're free to fall back on whatever other path was configured. 
----
[Contributor …
=> fix: Include /web check in notifications url eval

components/css/buckyless/header.less, components/css/buckyless/widget.less, components/portal/main/partials/header.html
- Added some CSS to maintain margins with or without side nav menu button
- Removed a little unused CSS
- Autohide menu tooltip so it doesn't linger on mobile
----
=> Fix spacing when app navigation isn't configured

components/portal/widgets/partials/type__search-with-links.html
The action url wasn't appearing because the variable name was mistyped.
Compare with [variable name in controller](https://github.com/uPortal-Project/uportal-app-framework/blob/5e78410d1d816e0d030eb366c8bed10f1830df01/components/portal/widgets/controllers.js#L190)
----
=> fix: Fix search widget type

components/css/buckyless/footer.less
Fix the circle character between footer links to one that renders on all os's
I didn't have a font that could have rendered 'black circle for record' (23FA), so I just got a fallback character of 'black circle' on my linux desktop.  So, now it uses 'black circle' (25CF) which was intended all along. 
Before on Android and OSX:
After on Android and OSX and Linux:
----
=> fix: circle character between footer links

components/portal/messages/controllers.js, components/portal/messages/services.js, docs/messaging-implementation.md
Causes a notification to reoccur every time a user opens a new session, until the user falls out of the targeted group or the notification expires.
----
=> feat: Recurring priority notifications

components/css/buckyless/directives/main-menu.less, components/css/buckyless/frame.less, components/css/buckyless/header.less, components/css/buckyless/widget.less, components/portal/main/controllers.js, components/portal/main/partials/body.html, components/portal/main/partials/header.html, components/portal/main/partials/main-menu.html, components/portal/messages/controllers.js, components/portal/messages/directives.js, components/portal/messages/partials/notifications-bell.html, components/portal/messages/partials/view__notifications.html, components/portal/messages/services.js, components/portal/misc/partials/frame-page.html, components/staticFeeds/sample-messages.json, docs/configuration.md
- Fixed a bug that caused the page to scroll automatically when the sidenav was opened (if there was overflowing content)
- Most CSS changes you'll see were made to accommodate this
- Fixed a bug where the notification bell didn't come back to the top bar after visiting the notifications page and then going elsewhere
- Fixed a bug where priority notifications were still displayed in the top bar while viewing the notifications page
- Fixed a bug where dismissing/restoring a priority notification didn't properly update the things that should be updated
- Gave the sidenav menu button its own controller so not to initialize the sidenav's controller twice
- Stopped passing controllers as scope objects on directives
- Instead, now using `messagesService` to broadcast when the …
=> fix: Stop auto-scroll and fix notification bugs

CHANGELOG.md, docs/make-a-widget.md
In prototyping recent list-of-links usage with UX consultant @mrdahman , title case rather than sentence case seemed to be preferable for the within-`list-of-links`-type-widget link labels.
This is at odds with the style recommendation currently embedded in the widget documentation (though interestingly the example screenshot in the documentation is already using title case rather than sentence case for this labelling). This changeset would update the guidance to match what we seem to now be preferring.
Personally, I'd have gone with sentence case. But this isn't about me personally. :) So this PR is about reconciling what professionally we ought to be recommending.
----
[Contributor …
=> docs: Recommend title case not sentence case for list-of-links labels

components/portal/messages/partials/notifications-bell.html
#601 appears to have introduced a bug that causes display of notifications to fail (which I am unable to produce locally). This PR adds tracking by index, which we should probably have anyway, and which might fix the bug.
----
=> fix: Track notifications by index to cope with duplicate values

components/portal/messages/partials/view__notifications.html
#602 fixed the bug, but we need the same fix on the notifications page.
*Note: This bug seems to have been caused by two notifications that have identical IDs -- in reality we should never encounter this issue as we are the gatekeepers of production notifications.*
----
=> fix: Add index tracking to notifications page

CHANGELOG.md
Catches up `CHANGELOG.md` to document the changes pending release, including an important breaking change, positing that the next release will therefore be a "major" release versioned `7.0.0`.
This makes the changelog more current, but probably is not sufficient documentation of just what the nature of the breaking change is and what upgraders should do about it when they upgrade.
----
=> Catch up changelog for putative 7.0.0 release

CHANGELOG.md, docs/make-a-widget.md
This commit reverts 793d59354a3522bb1c7bf4c0918f65a0e0658bfc ( #597 ).
There's some controversy about whether within-`list-of-links`-widget link labels are more usable as Title Case or as Sentence case and so what our style guidance ought to recommend, and how this relates to how literally we're adopting Material Design.
In the spirit of *stare decisis*, let's not change the recommendation at this juncture. This changeset reverts this guidance to the way it was in the most recent `uportal-app-framework` release so that the guidance does not change in this next release. Continue to think about it. It'll likely come up again. Maybe some future release will change this guidance if it ends up being important.
----
[Apereo CLA roster]: …
=> revert: docs: Recommend title case not sentence case for list-of-links

components/css/buckyless/directives/main-menu.less, components/css/buckyless/frame.less, components/css/buckyless/general.less, components/js/app-config.js, components/js/override.js, components/portal/messages/controllers.js, components/portal/messages/services.js, components/portal/widgets/partials/demo-widgets.html, components/portal/widgets/partials/type__action-items.html, components/portal/widgets/partials/type__list-of-links.html, components/portal/widgets/partials/type__option-link.html, components/portal/widgets/partials/type__rss.html, components/portal/widgets/partials/type__search-with-links.html, components/portal/widgets/partials/type__time-sensitive.html, components/portal/widgets/partials/widget-card.html, docs/make-a-widget.md, docs/widget-launch-button.md
[MUMUP-3146](https://jira.doit.wisc.edu/jira/browse/MUMUP-3146): "As a screen reader user, I would like widget launch buttons to have labels meaningful considered in isolation, so that I can exercise widgets effectively by stepping through the hyperlinks on the page."
- Resolves #608 
- Predefined widget types have launch button aria text of "Launch [widget title]"
- Updated docs to make guidance more visible for custom widgets
- Set redundant widget title to aria-hidden (title is included in the widget's first element, prior to description) to improve screen reader flow
- Continue flex-based model for push-content side navigation
- Move horizontal overflow limit to highest element (document body) to cope with potentially poorly-designed app content areas while using …
=> fix: Sensible aria labels for widgets, display bugs

components/portal/main/partials/main-menu.html
UX guidance suggested that the side navigation menu's subheading may be confused for a link by some users. This change aims to reduce that confusion.
----
=> fix: Clearer app menu subheading

CHANGELOG.md, components/css/buckyless/header.less, components/js/override.js, components/portal/main/controllers.js, components/portal/main/partials/header.html, components/portal/main/partials/main-menu.html
[MUMUP-3195](https://jira.doit.wisc.edu/jira/browse/MUMUP-3195): "As a MyUW app developer I would like uaf to stabilize, document, release notes confidently so it can release v7 so I have a concrete release to upgrade to with the side push menu feature."
- Fix a bug where the app menu button would appear even if app menu configuration flags were unset or wrongly configured
- Fixes a bug where setting `enablePushContentMenu` to true would show on-page menu content (footer links) and push the page over even if `appMenuItems` and `appMenuTemplateURL` are unset or wrongly configured
- Sets default configuration to not use side navigation menu (so simpler apps won't be forced to come up with side nav content)
- Remove some unused CSS
----
Contributor License Agreement …
=> Fix side nav bugs and update change log

CHANGELOG.md, components/portal/widgets/services.js, docs/make-a-widget.md, docs/widgets.md
Once upon a time we were trying to call the "store" of things in the portal a "marketplace" riffing on Apple and Google's "App Store" concept. We've since evolved to think of it as an "app directory". There's still remnants of calling it a "marketplace" in the JSON data model and in API paths, but at least this changeset normalizes "market" out of the documentation.
----
=> docs: normalize to prefer term "app directory" over "marketplace"

.github/CONTRIBUTING.md, CHANGELOG.md
Fixes #633 .
Acknowledges in `CONTRIBUTING.md` that we're trying to do Conventional Commits.
Adds hints on how to locally lint commit messages and even on how to automate this.
I think the hints work in that I locally followed my own instructions to re-add this pre-commit hook. (To be fair I was only able to do this by cribbing from the PR that removed the hook ( #581 ), so, hurray for clear, discoverable change history.).
Funny anecdote: The hook caught problems with my initial commit message attempt for ~~both~~ all three of these commits. Writing in Sentence case with a full stop. it's an ingrained habit.
----
[Contributor License Agreements]: …
=> docs(contributing): Note Conventional Commits and tips for complying

CHANGELOG.md, package.json
Since `lint-js` ignores docs, also ignore docs when JS-linting staged changes.
(I ran into this when touching `app-options.md`: while I didn't touch the example JavaScript, the example JavaScript failed `eslint`.)
Arguably we should be linting the JavaScript embedded in Markdown files -- but if we should, we should do so consistently.
----
=> build(lint-staged): suppress eslint on `docs/`

components/portal/messages/controllers.js, components/portal/messages/services.js
Emitting an event to the rootScope when a notification is dismissed causes all instances of the controller to reset properly, keeping the header bar in synch with the notification bell. 
----
=> MUMMNG-3983 Priority header synch with bell

components/css/buckyless/notifications.less, components/portal/messages/controllers.js, components/portal/messages/filters.js, components/portal/messages/partials/notifications-bell.html, docs/messaging-implementation.md, docs/text-guidelines.md
#610: "As a user with a priority notification with a (required!) action button, I would like that action button to afford room for a typical label, so I can read the label of the action button."
[MUMUP-3218](https://jira.doit.wisc.edu/jira/browse/MUMUP-3218): "As a MyUW user, I would like the priority notification text banner to artfully limit the characters so that I know if there is more text to see."
- Ensure notification buttons aren't clipped by limited space
- Enforce title length limit on priority notifications to guarantee consistent appearance
----
=> Improve priority notifications appearance

package-lock.json, package.json
npm <5.6.0 has issues with optional dependencies that are only installed for  particular operating system.
Causing dependencies such as `fsevents` to be added to the *package-lock.json* file on MacOS, but then be removed when a Linux system installs the project.
`npm >=5.6.0` includes a fix that normalizes handling of optional
dependencies to allow for any OS to produce that same *package-lock.json* file from a given *package.json*
reference: https://github.com/npm/npm/blob/latest/CHANGELOG.md#v560-2017-11-27
to update to the latest version of npm
```
npm install --global npm@latest
```
----
=> fix(package): require npm 5.6.0 or higher

appveyor.yml
Makes the unrelated "Error: EPERM: operation not permitted" errors going away.
This is a short term patch, https://github.com/uPortal-Project/uportal-app-framework/issues/346 is a better long term fix.
----
=> ci(appveyor): resolve require js flakiness

CHANGELOG.md
Trivial spelling and typo fixes in `CHANGELOG.md`.
----
=> docs(changelog): spelling and typo fixes

.travis.yml, package-lock.json, package.json
resolves #566, the deployment key based approach didn't work out.
If we want automated lockfile updates, renovate supports it without needing a secret key to be added to public CI.
----
=> refactor: remove greenkeeper lockfile

components/js/frame-config.js
Noticed typo.
Took a fresh stab at titling and describing this Beta Settings toggle.
After:
----
=> docs: clarify client-side message filtering disable toggle

components/portal/main/controllers.js, components/portal/main/services.js
No functional change.
Refactor to move the existing `setTitle()` function from the `PortalMainController` to the `mainService`.
This is a step towards making title setting available from more places and more dynamic, so that navigating within the app yields meaningful page titles describing where you are in the app, addressing WCAG2: 2.4.2:
> 2.4.2 Page Titled: Web pages have titles that describe topic or purpose. (Level A) 
Locally tested: status quo was that switching theme switches the page title to reflect the name of the portal per the selected theme. This still works with this changeset.
----
=> refactor: mv setTitle() to mainService from PortalMainController

components/portal/main/controllers.js, components/portal/main/services.js, components/portal/messages/controllers.js
Pulling the check for guest user into a service. Also, setting the default for the notification bell to be off until we verify it's an authenticated user.
----
=> fix: stop messages call for unauthenticated users

docs/make-a-widget.md
The example launchText had single quotes instead of the required double quotes
----
=> Fix example config

CHANGELOG.md, components/portal/widgets/partials/external-message.html
Trivially, changes the label from "Continue" to "OK" on the button for dismissing the dynamic interrupt-access-to-the-widget message.
This is intended to clarify, emphasize that this UI control is for just dismissing the cover, not addressing the issue the cover is communicating.
Motivating example: in MyUW we're using this feature to interrupt O365 users whose accounts are slated for de-provisioning to get their attention as they're trying to access those moribund accounts. The message is that their account will be terminated. We don't want them to be confused and think that "Continue" will somehow continue those accounts -- it won't, the UI control just lets them continue through to access the content *right now* regardless of the unchanged moribund nature of their O365 account.
[OK …
=> fix: "OK" rather than "Continue" on widget cover

CHANGELOG.md, components/portal/main/controllers.js, components/portal/main/main_service_spec.js, components/portal/main/services.js, components/portal/main/spec/main_controller_spec.js, components/portal/misc/app_header_options_controller_spec.js, components/portal/misc/controllers.js, components/portal/misc/directives.js, components/portal/misc/partials/app-header.html, docs/directives.md
Purpose:
* Set the document title to values describing the location in a `uPortal-app-framework` application as the user navigates within the application, thereby enabling improving usability generally and fulfilling `WCAG2: 2.4.2` specifically (Page Titled: Web pages have titles that describe topic or purpose. (Level A)).
Done:
* Adds title computation to `mainService`, implementing our (goofy?) "rule" about page naming, e.g. `PageName | AppName | PortalName`, with oodles of failing gracefully, and unit testing.
* Refactors title setting in `PortalMainController`, relying upon `mainService` to compute the title and only gathering the inputs and doing the view (Document) modification in the controller layer. This continues to mutate document title on theme change, since theme change can …
=> Reflect page title in document title

components/portal/widgets/directives.js
We've got outbound link analytics, but we don't have any analytics on internal widget interactions. This adds them to `a` tags within expanded and compact widgets.
I broke with outbound link style and used the href as the event label. I'd welcome an opinion as to why hrefs should be the event action.
----
=> feat: add analytics to widget interactions

components/css/buckyless/directives/add-to-home.less, components/portal/main/partials/example-page.html, components/portal/misc/controllers.js, components/portal/misc/partials/toast-add-to-home.html
[MUMUP-3299](https://jira.doit.wisc.edu/jira/browse/MUMUP-3299): As a person viewing an app via /web/exclusive or /web/static who does not yet have that app pinned to my home page, I would like to be able to add that app to my home page while viewing the app, so I can easily get back to the app later.
Also addresses the problem that the toast wasn't working as intended anywhere...
- Corrected template URL for custom toast
- Ensured dismissing it persists for session
- Ensured toast doesn't trigger if app already added to home
----
=> fix: fix add-to-home toast

components/portal/main/partials/header.html
Rather than hard-coding "MyUW", use `portal.theme.title`.
Defect:
Fixed:
One tiny step towards `uPortal-app-framework`'s aspirations for adoption beyond MyUW.
I think this is a regression since prior release rather than a fix of a previously existing bug, so no `CHANGELOG.md` update.
(Bug doesn't seem to exist in on-most-recent-release `qa.my.wisc.edu` e.g.)
----
=> fix: reflect portal title in header

CHANGELOG.md, components/portal/messages/controllers.js
moved showMessagesFeatures variable setting out of default, thus fixing a localhost bug
----
=> fix: move notification variable to appropriate logical point

CHANGELOG.md
This change: Reserve "Added" and "Changed" for features *of the product* added and changed. Move stuff about commit message style, linting, build automation, dependencies, etc. to a "Build engineering" section.
Context:
I was trying to put together the agenda for today's incubation check-in call, and found the `CHANGELOG.md` just a bit too noisy, not focusing enough on what changed *in the product*. KeepAChangeLog.com literally specifies just six categories of change to log, "Release engineering" not among them. But in spirit it's about "Changelogs are for humans not machines", and I think they're primarily for *adopter* humans. I think this change better addresses that spirit.
----
[Contributor …
=> docs(changelog): de-emphasize meta change

CHANGELOG.md, components/css/buckyless/directives/add-to-home.less, components/portal/misc/partials/toast-add-to-home.html
- Make toast message less cluttered by moving conditional text into toast text instead of into the button
----
=> style: improve appearance of add-to-home toast

CHANGELOG.md, components/portal/main/controllers.js, components/portal/main/partials/main-menu.html
[MUMUP-3295](https://jira.doit.wisc.edu/jira/browse/MUMUP-3295): "As a person navigating MyUW via keyboard, I would like focus to remain in (cycle through) the open hamburger menu until I dismiss the menu, so that the menu is more usable and so that my navigation is less confusing."
- When normal side navigation menu (i.e. _not_ push-content version) is open, keyboard navigation is trapped within the menu
- Tabbing past the bottom-most item results in focus resuming at the top-most item, and vice versa
----
=> feat: trap focus order within opened side navigation

CHANGELOG.md, docs/messaging-implementation.md
The example referenced widgetURL but should really reference widgetExternalMessageLearnMoreUrl.
----
=> fix: Corrected name of optional configuration setting

CHANGELOG.md, components/portal/widgets/controllers.js
Adding the logging I think I wish I'd had to support dynamic `list-of-links` troubleshooting.
----
=> feat: log bad dynamic response on dynamic list-of-links failure

CHANGELOG.md, components/portal/misc/partials/circle-button.html, components/staticFeeds/list-of-links-via-url.json, components/staticFeeds/sample-widget__list-of-links.json, docs/make-a-widget.md
Modest `list-of-links` quality of life improvements identified in the course of recently working on a list-of-links widget.
* **Formally deprecate Font Awesome icons in the context of `list-of-links`.**
* Accessibility improvement: don't truncate the `aria-label` view on the link title. Truncation navigates the tradeoffs of the visual effect of excessively long titles. In the case of a non-visual browser, this tradeoff should be navigated differently, in favor of the fuller title of what the thing is that's linked.
* Feature: add tooltip on `circle-button` offering the full link title in the case where the visual display of the title is truncated.
* Document `icon` in the context of `list-of-links` widget. (Also responsive to recent @jimhelwig feedback about the limitations of …
=> feat: add circle-button tooltips

CHANGELOG.md, components/staticFeeds/list-of-links-via-url.json, docs/make-a-widget.md
Demonstrate that a bare ampersand in the `list-of-links` JSON is just fine.
----
=> docs: demo ampersand in list-of-links link title

CHANGELOG.md, components/portal/messages/services.js
When filtering messages where one group name is a substring of another group name (e.g. "HRS Accessible Users" is a substring of "UW System HRS Accessible Users") - a bug exists where members of the longer group will also see messages intended only for members of the shorter group. 
----
=> fix: iterate through messages rather than filter

CHANGELOG.md, components/portal/widgets/partials/type__rss.html, docs/make-a-widget.md
In production MyUW, RSS widget news item titles truncate frequently. This improves, is necessary even, for home page display, but it's also annoying and erodes usability. Adding tooltips should allow university participants to better skim news as presented by the RSS widget type to decide whether to click to read articles.
Before ([publicly demonstrable on predev](https://public.predev.my.wisc.edu/web/apps/details/campus-news?q=news)):
----
=> feat: add md-tooltip when RSS item titles truncate

CHANGELOG.md, components/portal/main/partials/example-page.html, components/portal/widgets/partials/type__list-of-links.html, components/staticFeeds/list-of-8-links-via-url.json, components/staticFeeds/sample-widget__list-of-8-links.json, docs/make-a-widget.md
Recent work ( #727 ) added `md-tooltip` when titles presented via `circle-button` are truncated.
However, when `list-of-links` presents more than four links, it doesn't use `circle-button`s, it uses an ad-hoc list. This changeset adds an `md-tooltip` to cover this case as well. Also adds an un-truncated `aria-label`.
After:
----
=> feat: list-of-links tooltip when link truncated

CHANGELOG.md, components/portal/main/partials/example-page.html, components/portal/widgets/partials/type__list-of-links.html, components/staticFeeds/list-of-no-links-via-url.json, components/staticFeeds/sample-widget__list-of-no-links.json, docs/make-a-widget.md
`list-of-links` widgets can be configured with an array of zero links. This is especially plausible when sourcing the list of links from a dynamic remote feed (and indeed actually happens in representing HRS Portlet roles as a list-of-links).
Handle this case, degrading gracefully to present `list-of-links` widgets with zero internal links as `basic` widgets.
Before: blank widget face.
After (demo included in localhost example set):
----
=> fix: handle zero-links edge case in list-of-links

CHANGELOG.md, components/portal/messages/controllers.js
Only calls data urls for user-appropriate messages
----
=> fix: data urls processed only when needed

CHANGELOG.md, components/js/frame-config.js, components/portal/messages/controllers.js
+ Adds `showAllMessages` beta setting.
+ **Deprecates `disableGroupFilteringForMessages`** beta setting, which implements a subset of the effects of the new `showAllMessages` setting.
Client-side message filtering has evolved beyond just filtering by group membership. It now filters by date and by dynamic data. This new beta setting opts out of all that client-side filtering, enabling better demoing and testing of messages content.
Graceful deprecation. `disableGroupFilteringForMessages` still does exactly what it did before.
----
=> feat: add showAllMessages beta setting

CHANGELOG.md, components/portal/messages/partials/notifications-bell.html
Gives the user access to the full notification title when it's truncated for presentation in a priority notification banner across the top of the screen.
----
=> fix: tooltip when truncating priority notification title

CHANGELOG.md, components/portal/about/partials/about.html, components/portal/about/partials/session-info.html
- Links on "About" page work
- "Session info" page changed to "version info" (to match the name that content used to have when it was part of the "About" page)
----
=> fix: repair link binding and rename version info page

CHANGELOG.md, components/css/buckyless/directives/main-menu.less, components/css/buckyless/directives/username-menu.less, components/css/buckyless/features.less, components/css/buckyless/frame.less, components/css/buckyless/header.less, components/css/buckyless/notifications.less, components/css/buckyless/search.less, components/css/buckyless/widget.less, components/css/themes/common-variables.less, components/portal/about/partials/about.html
[MUMUP-3345](https://jira.doit.wisc.edu/jira/browse/MUMUP-3345): "Allow users to remove widgets that have an overlay"
- Widget remove button has higher priority than widget overlays
- Top-down adjustment of z-indices throughout app CSS (with LESS variables)
- Dialogs/toasts always on top
- Top bar higher than content
- Menus higher than the menu focus trap
- Widget actions higher than widget overlay
- Removed a couple unused/unnecessary z-index statements
----
=> fix: adjust z-indices to make widget actions available

CHANGELOG.md, components/css/buckyless/frame.less, components/css/buckyless/general.less, components/css/themes/common-variables.less, components/head-static.html
[MUMUP-3349](https://jira.doit.wisc.edu/jira/browse/MUMUP-3349): "As a uportal-app-framework developer, I'd like the Roboto web font preferred by default, so that my app can better adhere to Google Material guidelines."
- Made Roboto font available 
- Default to using Roboto
- Removed unused/inaccessible CSS
----
=> feat: Add and use Roboto web font

CHANGELOG.md, components/portal/messages/partials/notifications-list-item.html
[MUMMNG-4140](https://jira.doit.wisc.edu/jira/browse/MUMMNG-4140): "As an end user clicking on external notification links, I want them to open in a new window so that I don't want to lose track of my MyUW session."
- Action button links on notifications page open in new tab
- *Note: This is the same behavior as notifications in the bell menu.*
----
=> fix: open notification links in new tab

CHANGELOG.md, components/css/buckyless/widget.less, components/portal/widgets/partials/widget-icon.html
Fixing/adding functionality to be able to use custom SVGs.
Retained ability to display PNG images as icons.
----
=> feat: update svg functionality to use mdIcon

CHANGELOG.md, components/head-static.html, components/portal/about/controllers.js, components/portal/about/services.js, components/portal/main.js, components/static.html, components/staticFeeds/about-page.json, docs/about-page.md, docs/configuration.md
[MUMUP-3348](https://jira.doit.wisc.edu/jira/browse/MUMUP-3348): "As a uaf developer, I'd prefer my app to not include UW-Madison-related meta information, so that my non-UW app doesn't have a MyUW description/keywords."
- Replace hard-coded meta tags with tags sourced from the new `aboutPageURL`
- Downstream impact should be negligible, as the existing implementation identifies all apps as "MyUW." Companion PRs for actual MyUW can be found [here](https://git.doit.wisc.edu/myuw-overlay/uportal-home-overlay/merge_requests).
- Set "About" information during bootstrapping phase (with app-wide availability)
- Remove now-unused service method to get "About" information
- Update docs to describe new functionality
- Set Roboto font in static loading page (for consistency's sake) …
=> feat: source meta info from about page url

CHANGELOG.md, components/css/buckyless/header.less, components/js/app-config.js, components/portal/main/partials/main-menu.html
[MUMUP-3363](https://jira.doit.wisc.edu/jira/browse/MUMUP-3363): "As a user of MyUW, I would like to not see the 'What's New' link in MyUW that links to an empty page, so that I'm not confused at the empty page."
- Remove link to /features from default footer configuration
- Remove left-margin from theme/portal name on small screens (save space)
----
=> Remove "What's New" from footer(s) and adjust header CSS

CHANGELOG.md, components/css/angular.less, components/css/buckyless/base.less, components/css/buckyless/features.less, components/css/buckyless/md-generated.less, components/css/buckyless/widget.less, components/portal/misc/controllers.spec.js, components/portal/timeout/controllers.js, components/portal/timeout/session-expired.html
[MUMUP-3364](https://jira.doit.wisc.edu/jira/browse/MUMUP-3364): "As a user of Advising Gateway, I would like the session expired message to not be blocked by other items such as drop downs, so I can interact with the session expired message and log in again."
- Increased z-index of all dialogs to the highest in-framework value (101)
- *Note: Any downstream apps that still have problems with content obscuring these dialogs should adjust the z-index value of that content*
- Made session timeout dialog look like other dialogs used in the framework
- Fixed a bug that was causing the backdrop behind dialogs to appear transparent
- Add new `<body>` styles to replace the ones being brought in by Bootstrap
- Ensures Robot font is used everywhere (never overridden by Bootstrap)
- …
=> Fix presentation of dialogs (and other CSS tweaks)

docs/make-a-widget.md
Documents in the widget-developer-facing documentation #772 's change to reduce `list-of-links` link quantity limit to 6 from 7.
The functional change is to address a display issue where, depending on icon choice, the list could vertically exceed the widget  box.
=> docs: document in list-of-links that limit reduced to 6

docs/make-a-widget.md
Duplicate headings within Markdown file impairs deep linking (because of ambiguous generated anchors) and impairs accessibility (navigation by heading). So avoid duplicate heading labels.
=> docs: avoid duplicate headings

components/css/buckyless/exclusive-mode.less, package-lock.json, package.json
- Fix missing generic font family specifier in exclusive mode styles
- Turn off new stylelint rule to enable #701  to pass linting
----
=> chore: upgrade stylelint and turn off new rule

CHANGELOG.md, components/css/buckyless/widget.less
- Fixes date text overlapping title text on some screen sizes
----
=> style: set no overflow on rss titles

CHANGELOG.md, components/css/buckyless/md-generated.less, components/css/buckyless/widget.less, components/js/override.js, components/portal/widgets/partials/widget-card.html
[https://jira.doit.wisc.edu/jira/browse/MUMUP-3297](MUMUP-3297): "As a person navigating MyUW via keyboard, I would like the less-often-used controls associated with widgets on my home tucked away into a contextual menu, so that the primary navigation is simpler."
**Companion PR:** [uportal-home #840](https://github.com/uPortal-Project/uportal-home/pull/840)
- Move widget info (description) and remove button into single contextual menu
- Make widget title focusable 
- Added another demo configuration for local development to `override.js` 
----
=> feat: add contextual menu for widgets

CHANGELOG.md, components/portal/widgets/partials/compact-widget-card.html, components/portal/widgets/partials/widget-card.html
The div will exist many times in the page, yielding [duplicate div ids forbidden by HTML spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id) .
Fortunately, we're not using this div (it has no references in `uportal-app-framework` nor in `uPortal-home`). So drop the `id` attribute, resolving the uniqueness constraint violation and simplifying the code. Win-win.
----
=> fix: rm unused not-unique "widget-removal" div id

CHANGELOG.md, components/portal/misc/filters.js
add filter on whether the user can or cannot add the given portlet to layout.
Potentially useful in resolving the mismatch between reported and shown quantity of app directory search results, since that turns out to be a difference of including items one cannot add in the badge count while not displaying such items.
----
=> feat: add canAdd filter

CHANGELOG.md, components/portal/main/partials/example-page.html
Adds compact mode widget examples to the existing examples page that had only shown expanded mode widget examples.
----
=> feat: add compact mode examples

CHANGELOG.md, components/portal/widgets/controllers.js, components/portal/widgets/partials/widget-card.html
- Pressing "enter" when focusing the widget removal transclude slot now correctly triggers a click event on the transcluded button
----
=> fix: enable activating remove button with keyboard

CHANGELOG.md, components/portal/settings/controllers.js, components/portal/settings/partials/user-settings.html
This change removes the unused photo option from the user-settings page. (We can always put it back if we plan to implement that feature.)
----
=> MUMUP-3379: removes unused avatar setting

docs/messaging-implementation.md
Captures to documentation clarification that arose in answering a question about whether multiple action buttons are available per message.
Also fixes a text styling glitch.
=> docs(messages): clarify that at most one of each button type per message

docs/make-a-widget.md
Fix the "Predefined widget types" bulleted list in
`make-a-widget.md` to include bullets for the "Action items" and "Time-sensitive-content" types, which types are documented in that file.
=> docs(widgets): list all documented widget types

CHANGELOG.md, components/portal/widgets/partials/widget-card.html
When the framework does not recognize a widget type, fall back to handling it as if it were a `basic` widget.
Before:
(Widget with unrecognized type renders broken. Can't even launch it.)
After:
(Widget with unrecognized type renders as if it were a `basic` widget. At least I can launch it.)
----
=> feat(widgets): default to `basic` when type unrecognized

README.md
Running `uportal-app-framework` locally demos a lot better if you first configure it a bit. This change adds hints to README on what configuration to do.
----
=> docs(readme): doc setting app-config for localhost demo

CHANGELOG.md, components/portal/main/partials/example-page.html, components/portal/widgets/controllers.js, components/portal/widgets/directives.js, components/portal/widgets/partials/type__basic.html, components/portal/widgets/partials/type__switch.html, components/portal/widgets/partials/widget-card.html, components/portal/widgets/partials/widget-content.html, components/staticFeeds/enrollment-flag-H.json, components/staticFeeds/enrollment-flag-O.json, components/staticFeeds/enrollment-flag-Z.json, components/staticFeeds/sample-widget__switch.json, components/staticFeeds/sample-widget__switch_2.json, components/staticFeeds/sample-widget__switch_broken.json, components/staticFeeds/sample-widget__switch_otherwise.json, docs/make-a-widget.md
Adds a new `switch` widget type, a meta widget that switches to become another widget type depending upon a dynamic value.
+ The `widgetURL` is the source for the dynamic JSON to evaluate.
+ Evaluates an AngularJS `expression` on that JSON to extract a value.
+ Matches that value against one or more `cases` configured in `widgetConfig`.
+ The matching case, or a default `caseotherwise` case, may specify a new `launchText`, widget type, `widgetConfig`, or even a new URL from which to source JSON to drive the newly selected widget type.
See [documentation for the new widget, added in this changeset](https://github.com/uPortal-Project/uportal-app-framework/blob/eccf6b0ea0a9a4613f20ac3fea0d1a7e40c94417/docs/make-a-widget.md#switch-widget-type).
Adds example widget publications in `localhost` …
=> feat(switch): add "switch" widget type

CHANGELOG.md, components/portal/main/partials/example-page.html, components/portal/widgets/controllers.js, components/portal/widgets/partials/type__list-of-links.html, components/staticFeeds/list-of-one-redundant-link-via-url.json, components/staticFeeds/sample-widget__list-of-one-redundant-link.json, docs/make-a-widget.md
Status quo `list-of-links` widget had a feature where it would try to detect when the widget would be trivial (displaying only a single link redundant with the link the launch button would link) and collapse to a `basic` type widget in this case.
However, in at least some cases the widget wasn't doing this, as demonstrated by a `localhost` example added in this changeset.
Added example before fix:
Looks like there'd been some code at the controller layer to try to detect and handle this case, and that it didn't always fire. This changeset moves responsibility for handling this case into the `list-of-links` partial so that this handling will apply regardless of how the framework gets to that partial.
After:
----
[Apereo CLA roster]: …
=> fix(listoflinks): collapse trivial list-of-links to basic type widget

CHANGELOG.md, components/portal/widgets/controllers.js, components/staticFeeds/sample-widget__switch.json, components/staticFeeds/sample-widget__switch_2.json, components/staticFeeds/sample-widget__switch_broken.json, components/staticFeeds/sample-widget__switch_otherwise.json, docs/make-a-widget.md
Adopt`defaultCase` as a better name than `caseotherwise` as the none-of-the-cases-matched case in the new `switch` type widget.
[Naming things is hard](https://martinfowler.com/bliki/TwoHardThings.html), and [important](https://twitter.com/i/web/status/1032267640033538048).
----
=> feat(switch): rename `caseotherwise` to `defaultCase`

CHANGELOG.md, components/portal/main/partials/example-page.html, components/staticFeeds/sample-widget__time-current.json, components/staticFeeds/sample-widget__time-expired.json, components/staticFeeds/sample-widget__time-future.json, components/staticFeeds/sample-widget__time-past.json, components/staticFeeds/sample-widget__time-soon.json
Adds `localhost` examples demonstrating the `time-sensitive-content` widget across most of its lifecycle.
----
=> feat(examples): add examples of time-sensitive-content widgets

CHANGELOG.md, components/portal/timeout/controllers.js, docs/configuration.md
Because the uPortal session hasn't actually died after an inactive timeout occurs, going directly to loginURL causes you to be automatically re-logged in. What we actually want is for the user to be explicitly logged out due to inactivity.
----
=> fix: use logoutURL for inactive timeout

CHANGELOG.md, components/portal/widgets/controllers.js, components/portal/widgets/partials/type__action-items.html, components/staticFeeds/sample-widget__action-items_one.json, components/staticFeeds/sample-widget__action-items_partially-broken.json, components/staticFeeds/sample-widget__action-items_totally-broken.json, docs/make-a-widget.md
Improving error handling in `action-items` widget type, trying to un-block the "HRS Approvals" widget going to production in MyUW (currently blocked by insufficiently clear failure experiences that might detract from smooth launch of incremental self-service approvals functions).
Allows action item types within an `action-items` widget to independently fail and acknowledges the failed item types by name.
After:
Before:
----
=> feat(action-items): add more error handling

components/portal/messages/services.js
Fixes a trivial typo in an inline comment in the source code.
----
=> docs: fix trivial typo "us it" --> "use it" (inline source code comment)

CHANGELOG.md
+ Fix incorrect references to #836 that were meant to be references to #838
+ Remove incorrect duplicate references to #830 and #832 that would describe these as new in the next release, whereas they were included in already-released 10.3.0.
In general, appease the Markdown linter. In specific,
+ Avoid duplicate heading labels, thereby avoiding ambiguous generated hyperlinks to headings.
+ Wrap at 80 characters.
+ Normalize blank lines.
+ Normalize bullets and bullet list indentation.
----
=> docs(changelog): correct and clean up CHANGELOG

CHANGELOG.md, components/portal/widgets/partials/type__time-sensitive.html, docs/make-a-widget.md
Show the feedback link in the `time-sensitive-content` widget only after the action period has expired.
The idea is that while the primary action is available, feedback is more distraction than it's worth. User can still more generally provide feedback through e.g. the footer feedback link. It's only after the action period is over that feedback is the primary action available to the user about the time sensitive activity that a `time-sensitive-content` widget is about.
Before:
After:
----
------
Tracked internally to MyUW as [MUMUP-3406](https://jira.doit.wisc.edu/jira/browse/MUMUP-3406).
=> feat(timesensitive): suppress feedback link during action period

CHANGELOG.md, components/portal/main/partials/example-page.html, components/portal/widgets/partials/type__list-of-links.html, components/staticFeeds/list-of-four-links-first-redundant-via-url.json, components/staticFeeds/sample-widget__list-of-4-links-first-redundant.json
`list-of-links` has a feature where when it's configured with a single link redundant with the widget launch bar, it collapses to a basic widget as the  preferred way to present a single hyperlink. That feature was bugged (my bad) so that it would suppress 2-4 link list-of-links widgets when the first link matched the launch bar. This fixes the bug, adding to localhost content a demo of the fixed case.
Before:
After:
----
----
Tracked within MyUW as [MUMUP-3411](https://jira.doit.wisc.edu/jira/browse/MUMUP-3411).
=> fix(list-of-links): multiple links when first redundant with launch bar

CHANGELOG.md, docs/make-a-widget.md
I got confused about how to configure `takeActionEndDate` such that [MyUW Benefit Information widget prematurely told employees today was last day to enroll](http://outages.wisconsin.edu/outage/9441e5d983aa1bd08e4d7447e7b974e89e6e151f98), whereas tomorrow is actual last day to enroll. Updating documentation with clarity that might have supported my correctly configuring the widget.
----
----
Tracked as [MUMUP-3420](https://jira.doit.wisc.edu/jira/browse/MUMUP-3420) locally to MyUW.
=> docs(timesensitive): clarify takeActionEndDate

CHANGELOG.md, components/portal/timeout/controllers.js, docs/configuration.md
On warning, prompt the user to make an ajax call, and restart the timer.
On timeout, prompt the user to reload the page.
----
=> fix: use less disruptive actions for inactivity timeout

CHANGELOG.md, components/portal/widgets/partials/type__action-items.html, docs/make-a-widget.md
Adds a special error case to `action-items` widget type.
Back story: the HRS Approvals widget failed for a while in production. It shows a single action-items indicator telling the employee how many thingies they have awaiting their approval in HRS. During this extended failure period, it showed its fancy complicated error message. Which led to the UX insight/perspective/advice that really we're not doing employees any favors with that fancy error message in this case. When its sole indicator fails, it's a complicated single hyperlink. So in that case let it be a regular old simple single hyperlink.
In the special case where `action-items` is configured with one indicator and that one indicator fails, degrade to a `basic` widget.
Don't do this when there are multiple indicators, since …
=> fix: gracefully degrade action-items to basic when sole indicator errors

components/css/themes/common-variables.less, components/css/themes/uPortal-variables.less, components/css/themes/uwColleges-variables.less, components/css/themes/uwEauClaire-variables.less, components/css/themes/uwExtension-variables.less, components/css/themes/uwGreenBay-variables.less, components/css/themes/uwLaCrosse-variables.less, components/css/themes/uwMadison-variables.less, components/css/themes/uwMilwaukee-variables.less, components/css/themes/uwOshkosh-variables.less, components/css/themes/uwParkside-variables.less, components/css/themes/uwPlatteville-variables.less, components/css/themes/uwRiverFalls-variables.less, components/css/themes/uwStevensPoint-variables.less, components/css/themes/uwStout-variables.less, components/css/themes/uwSuperior-variables.less, components/css/themes/uwSystem-variables.less, components/css/themes/uwWhitewater-variables.less, components/main.js, components/portal/main/controllers.js
Attempting to combat the huge slowdown the "watch" configuration causes in IE11. Adding var definitions to ":root" because apparently that's the only way the css-vars-ponyfill works... if that's true, then I don't understand why it worked with the watch config.
----
=> fix: rm watch, put css vars in :root for polyfill

components/portal/main/controllers.js
Tested this out and found adding this on the portal.theme watch did not improve the experience. Removing this call in preference for main load call.
----
=> fix: rm cssvars call on theme watch

CHANGELOG.md, components/static.html
- When user closes IE alert, add a cookie with 20-day lifespan
----
=> feat: add cookie to limit ie alert frequency

CHANGELOG.md, package-lock.json
I don't know what I'm doing here.
I locally try to  `mvn -DdryRun=true release:prepare`.
It fails because my `package-lock.json` locally changes.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.1:prepare (default-cli) on project uportal-app-framework: Cannot prepare the release because you have local modifications : 
[ERROR] [package-lock.json:modified]
```
These are the local changes.
----
=> build: update package-lock.json to remove optional markings

CHANGELOG.md, components/css/buckyless/notifications.less, components/portal/main/controllers.js, components/portal/main/partials/main-menu.html, components/staticFeeds/sample-messages.json, docs/messaging-implementation.md, docs/messaging.md
Updates documentation to reflect that the "priority" notification feature is deprecated, getting slightly in front of intent to replace with a new banner message feature hewing a bit closer to (spirit of?) Material Design and reducing complexity of notifications as such.
----
=> docs: deprecate "priority" notifications

CHANGELOG.md, components/portal/main/services.js, components/staticFeeds/sample-banners.json, docs/messaging-implementation.md
Banner messages service expected to send a bare array of messages, but framework had expected this to be in a `messages` key; removing messages key to align expectations of banner message feed producer and consumer.
----
=> fix: banner messages as bare array

CHANGELOG.md, components/head-static.html
Import new `myuw-help-link` web component so that content in the portal can use it to link to help.
----
=> Add myuw-help-link web component

CHANGELOG.md, components/portal/timeout/controllers.js
- Don't display additional "session expired" dialog if one is already being displayed.
----
=> fix: prevent multiple session expired dialogs from displaying

CHANGELOG.md, components/static.html
- Replace "Loading..." splash screen with a generic content preview screen
- Include screen-reader-only heading to indicate loading
- Preview content has a gradual pulse animation to give the impression that it's in progress
Apple, Facebook, and other high-profile web presences have agreed that skeleton screens build anticipation for content, whereas loading spinners/screens put the focus on the wait time that the user has to endure. Also...this is just nicer to look at. :)
*Note: This doesn't solve the problem of un-styled content flashing during angularjs bootstrapping, but it's still an improvement in my view.*
----
[Contributor License Agreements]: …
=> feat: replace "Loading..." screen with animated content preview

CHANGELOG.md
#897 's changelog update had a typo, this fixes it.
----
=> docs(changelog): fix typo "exipred" --> "expired"

CHANGELOG.md, components/portal/widgets/partials/type__action-items.html, components/portal/widgets/partials/type__basic.html, components/portal/widgets/partials/type__list-of-links.html, components/portal/widgets/partials/type__rss.html, components/portal/widgets/partials/type__search-with-links.html, components/portal/widgets/partials/type__time-sensitive.html, components/portal/widgets/partials/type__weather.html, components/staticFeeds/sample-widget__list-of-8-links.json, docs/make-a-widget.md
Adds support for new `widgetConfig` fields `launchUrl` and `launchUrlTarget`, parallel to `launchText`, that further customize the expanded mode widget launch bar.
Allows specifying that the expanded mode widget launch bar should link elsewhere than the `alternativeMaximizedLink` of the overall `portlet-definition`. So that, say, the alt max link can link to the expanded mode of the widget, and then the expanded mode widget can link to somewhere that is not the expanded mode widget, for those cases where the expanded mode widget is the next thing to launch when it's not what you're currently looking at.
----
=> feat: widgetConfig.launchUrl

CHANGELOG.md, components/head-static.html
It turns out `myuw-help-link` is no longer used anywhere, and so doesn't need to be included in the page by the framework.
(It didn't reliably render in hrs-portlets, workaround was to implement the UI component as a custom JSP tag instead.)
----
=> fix: rm myuw-help-link web component

CHANGELOG.md, components/static.html
#898 changed the loading indicator. It introduced a for-typical-browsers visual experience that disappears when loading completes. It also introduced a screen-reader-only h1 indicating that the page is loading, bugged such that the h1 persists after the application has fully loaded.
This change moves that screen-reader-only `<h1` into the `<div` predicated on loading, so that screen readers and typical browsers have a more equivalent experience of the loading indicator.
----
----
Tracked internally to MyUW as [MUMUP-3469](https://jira.doit.wisc.edu/jira/browse/MUMUP-3469).
=> fix: move the sr-only h1 loading message into div conditioned on loading

CHANGELOG.md, components/portal/widgets/partials/type__list-of-links.html, components/staticFeeds/sample-widget__list-of-links.json, docs/make-a-widget.md
There's long been a documented feature of `list-of-links` that would suppress the expanded mode widget launch button (bar) in the case where `widgetConfig.launchText` is not set.
That feature didn't actually work. But the Thumper Principle is a pretty good one. When the launch bar adds no value beyond the foregoing list-of-links, we should not show it. So this pull request (re-)adds the feature, this time triggering it more explicitly so that omitting `launchText` can continue to yield the default show-launch-button-with-default-text behavior.
----
=> feat: invent `list-of-links` `widgetConfig.suppressLaunchButton`

CHANGELOG.md, components/portal/main/partials/example-page.html, components/portal/widgets/controllers.js, components/portal/widgets/directives.js, components/portal/widgets/partials/type__remote-content.html, components/portal/widgets/partials/widget-content.html, components/staticFeeds/remoteWidgetExample.html, components/staticFeeds/sample-widget__remote.json, docs/make-a-widget.md
Adds new widget type `remote-content` that shows a loading indicator until it can swap in markup sourced from a URL.
With this technology, widgets can be implemented in JSP, PHP, ...
It's a hammer. Not every problem is a nail. Some are. 🔨  💅 
----
=> add remote-content widget type

CHANGELOG.md, components/config.js
Upgrades to [AngularJS 1.7.8](https://github.com/angular/angular.js/blob/master/CHANGELOG.md#178-enthusiastic-oblation-2019-03-11) from 1.7.2, picking up some bug fixes.
----
=> fix: upgrade to angularjs 1.7.8 from 1.7.2

CHANGELOG.md, components/portal/main/partials/example-page.html, components/portal/widgets/controllers.js, components/portal/widgets/directives.js, components/portal/widgets/partials/widget-card.html, components/portal/widgets/services.js
This allows invoking `<widget>` in contexts where it's not clear the viewing user will be able to see that widget or even that the widget exists at all. Imagine pages with suggested widgets that gracefully degrade to what's working and permitted to the viewing user.
----
=> Add optional `fail-silently` attribute on `widget` directives

CHANGELOG.md, components/portal/search/partials/search.html
Clarifies what sort of searching users might do. Intended to make the search bar more usable by giving users more of a hint of what they might usefully type in that box.
"Search for apps by keyword..."
----
----
[MUMUP-3489](https://jira.doit.wisc.edu/jira/browse/MUMUP-3489) as tracked internally to the MyUW project.
=> Change prompt text within search bar

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
Review of MyUW against the (UW Office of Cybersecurity) [Risk Management Framework](https://it.wisc.edu/about/division-of-information-technology/strategic-operations-departments-people/cybersecurity/risk-management-framework) flagged a need to add process to ensure changes are reviewed for security impact.
This PR would add a checkbox to the Pull Request template to remind to examine changes for security impact.
----
---- 
Tracked internally to MyUW as [MUMMNG-4658](https://jira.doit.wisc.edu/jira/browse/MUMMNG-4658).
=> docs: add reminder to examine changes for security impact to PR template

CHANGELOG.md, components/portal/messages/controllers.js, components/portal/messages/services.js, docs/messaging-implementation.md
Not reliably working: rather than dismissing for session, dismissing a recurrence=true message would result in the message immediately being un-dismissed.
----
Low security risk: this change is about whether and how a message displays has handled client-side in the UI, not about whether the message is available to the client in the first place.
----
----
Tracked internally to MyUW as [MUMUP-3491](https://jira.doit.wisc.edu/jira/browse/MUMUP-3491).
=> fix(messages): remove broken experimental `recurrence` property of msg

CHANGELOG.md, components/portal/widgets/partials/compact-widget-card.html, components/portal/widgets/services.js
This reverts commit 9643edefefb904c34b5e02e908680bdf949a5ba4.
This backs out using the `myuw-compact-card` web component to implement compact cards, thereby avoiding the regressions and incomplete icon support in compact mode introduced by that attempt at implementing that feature as a web component.
Attempting to get stable with a more modest framework changeset to ship a release.
----
=> Revert "feat: use new myuw-compact-card web component (#932)"

components/head-static.html
Fixes import of the new `myuw-help` web component to do so over https: to avoid Chrome zealously blocking the import.
----
=> fix: source myuw-help via https rather than http

docs/releasing.md
We no longer deploy to docker.doit.wisc.edu and haven't for a long time.
----
=> docs(releasing): remove Docker release section

CHANGELOG.md, components/css/buckyless/header.less
`overflow-y: hidden` was preventing Help Dialog from proper display, on top of the app's body. This change prevents the dialog from "showing" behind the content, and being unreachable.
=> Update overflow-y of portal-header

CHANGELOG.md, components/css/buckyless/base.less
[Travis-CI build on master has been failing](https://travis-ci.org/github/uPortal-Project/uportal-app-framework/builds/667419906?) because of some linting failures.
This pull request
+ resolves a LESS linting failure by normalizing an indent
+ resolves a couple missing PR reference links in the CHANGELOG by adding the missing definitions
+ resolves undefined version reference links in the CHANGELOG by removing the links from version number to diff. In practice those links are tedious to maintain and have proven a repeated area of errors and linting failures over time. Reduce commitments to low value manual work.
----
[Apereo CLA roster]: …
=> Resolve linting errors in travis-ci build

.github/CONTRIBUTING.md, docs/releasing.md
Another changeset had re-introduced Markdown linter failures by removing usages of reference links without removing the definition of those links.
This fixes that issue and also updates the CONTRIBUTING documentation to remind that linting is a thing and can be run locally.
----
=> Clear more linter warnings

CHANGELOG.md, components/css/buckyless/header.less, components/head-static.html, components/portal/main/partials/header.html, components/portal/main/partials/main-menu.html
+ Update paths to settings pages
+ Remove Guest Login button, which now is taken care of by myuw-profile component
----
- [x ] The change has been examined for security impact.
- [x ] Updates `CHANGELOG.md` to reflect this PR's change.
- [ x] This Contribution is under the terms of Individual [Contributor License Agreements][] (and also Corporate Contributor License Agreements to the extent applicable) appearing in the [Apereo CLA roster][].
=> Updates to implementation of myuw-profile web component

CHANGELOG.md, components/config.js
Downgrading angular-resource in the hope of better supporting upgrading apps using that version of angular-resource.
----
=> Downgrade angular-resource to 1.5.8

CHANGELOG.md, components/portal/main/partials/example-page.html, components/portal/widgets/directives.js, components/portal/widgets/partials/widget-card.html, docs/widgets.md
Adds optional `include-context-menu` attribute on `widget` directive. Defaults to `true`. When set to `false`, suppresses the upper right context menu on widgets.
----
=> condition widget context menu on optional attribute include-context-menu

CHANGELOG.md, components/css/buckyless/md-generated.less, components/head-static.html, components/portal/messages/controllers.js, components/portal/messages/partials/notifications-list-item.html, components/portal/messages/partials/view__notifications.html
- Update `myuw-notifications` to v1.3.3
- Fix page-breaking injection error
- As`md-list-item` appends empty `md-secondary` element to DOM, change style of `notifications-list-item`: `width: 100%`
=> bugfix: empty notifications page

components/css/buckyless/md-generated.less, components/portal/messages/partials/notifications-list-item.html, components/portal/messages/partials/view__notifications.html
Fix 'See all' notifications page styles
- add a bottom border for each notification item
- add vertical padding for each notification item
- realign action buttons
- set high priority text bold
=> Fix 'See all' notifications page styles

CHANGELOG.md, components/portal/main/partials/header.html, components/portal/main/partials/main-menu.html
I would like to propose displaying the Notifications bell icon in the header (since there's an estate for it) at all times rather than hiding it in the Sidenav.
----
=> Improve visibility of Notifications button

CHANGELOG.md, components/portal/widgets/partials/type__option-link.html
Okay, this kind of fun.
In practice, the only usage of option-link in MyUW is for the O365 email integration.
Most users have one email address. Some have several. Hence the use case for option-links, so they can select which to launch. Some have zero, as in the case where they're eligible to activate but have not yet activated.
In practice, the only [option-link usage is in singleElement mode](https://git.doit.wisc.edu/myuw-overlay/entities/-/blob/prod/src/main/resources/portlet-definition/wisc-mail.portlet-definition.xml#L98).
In practice, when the user has no email address, `!widget.widgetData[config.display]` will evaluate true. [("display" is set to "email" in the widgetConfig](https://git.doit.wisc.edu/myuw-overlay/entities/-/blob/prod/src/main/resources/portlet-definition/wisc-mail. …
=> Gracefully handle the case where a user has zero email addresses

CHANGELOG.md, components/js/ga.js, docs/Google-analytics.md, src/main/webapp/frame.jsp, static/index.html
A more surgical version of #998 .
Stops *initializing* Google Analytics while continuing to add our special sauce for eventing on outbound links.
=> Rely on Google Tag Manager to init Google Analytics

components/portal/misc/services.js
Rather than pushing events directly to Google Analytics.
=> push analytics events to Google Tag Manager dataLayer

components/portal/misc/services.js
#1000  had introduced JavaScript style errors that fail JavaScript linting.
This should address those issues so that the linter passes again.
=> Address JavaScript linter complaints

docs/messaging-implementation.md
The status quo documentation is incorrect in several respects. This fixes the documentation, validated by what works for the new tablecloth message being deployed over the STAR widget.
=> Fix documentation about "tablecloth" messages over widgets

components/js/ga.js
testing in predev: the instrumentation on the links is firing. `ga.js` attempts to publish the event to `window.ga` ... but that doesn't apparently result in the event actually going to Google Analytics.
From the console log:
```
ga event logged c: Outbound Link a: https://people.extension.wisc.edu/ l:
people
```
So. With this change, `ga.js` instead attempts to publish the event to the new (global) `dataLayer` provided by Google Tag Manager, ala `portal.misc.services`.
Don't know if this is going to work. Let's try it.
=> push Outbound Link events to Google Tag Manager rather than direct to ga

CHANGELOG.md, components/head-static.html
Upgrades to [myuw-banner version 1.2.3](https://github.com/myuw-web-components/myuw-banner/blob/master/CHANGELOG.md#123), which styles more compactly at wide screen widths.
Allows retiring the [local overlay patching head-static](https://git.doit.wisc.edu/myuw-overlay/uportal-home-overlay/-/blob/prod/src/main/webapp/head-static.html) to use this version of myuw-banner.
=> Update myuw-banner to v1.2.3

CHANGELOG.md, components/portal/misc/services.js
Intended to support newly generated `401 Unauthorized` from uPortal server.
With this change, when uPortal responds `401 Unauthorized` when it loses the plot of the user session, app framework will redirect user to log in again.
----
=> do not predicate miscService.redirectUser on status code

CHANGELOG.md, components/portal/timeout/services.js
Shibboleth JSON 404s expectedly on public.my sites, so stop those expected failures from causing an infinite login redirect loop.
----
=> don't redirect for login on failure of Shibboleth JSON

CHANGELOG.md, components/portal/misc/services.js
On reflection, https://github.com/uPortal-Project/uportal-app-framework/pull/1014 went too far in making *any* status redirect the user in miscService.redirectUser(). In particular this made 404s redirect. 
Instead, add status 401 specifically to the statuses that cause redirects. This will keep the newfound support for detecting when APIs are failing because the user isn't logged in and for automatically handling this case, with fewer under-considered side effects.
----
=> Redirect in miscService.redirectUser on 401, 302, and 0 specifically

CHANGELOG.md, components/portal/misc/partials/circle-button.html
Makes the text label of `circle-button` (used on widgets like `list-of-links` and `search-with-links`) clickable with the same effect as the icon circle part of the button. 
This improves usability by offering a larger click target. Clicking the label clearly expresses user intent to launch the link, so it should launch the link, rather than requiring the user to hone in on the circle icon bit.
The implementation is a little weird in that there are two redundant links, with the new link kept out of keyboard tab navigation. This is because I didn't immediately find a way to get this down to one hyperlink in the DOM. That would be more semantic and it would be more usable if hovering over either the text or the icon actuated the hover UI treatment on both, reinforcing to the user that they …
=> Bigger circle-button click targets (for example, in list-of-links)

CHANGELOG.md, components/portal/misc/services.js
miscService.redirectUser exists to redirect the user back through uPortal login in the case where it seems that API calls are failing because no longer logged in.
One big downside of that is losing the user's place in the application. They end up back at the uPortal-home main page (`/web`).
This Pull Request improves upon that status quo by leveraging uPortal server's existing `refUrl` feature. This sets `refUrl` on the redirect to uPortal Login, so that once uPortal Login has re-established a logged in uPortal session, *uPortal Login redirects back to the refUrl rather than to the uPortal-home front page*, and thus the logging back in is less disruptive, returning the user to where they were.
----
=> Set uPortal refUrl on the redirect to login

CHANGELOG.md, components/js/app-config.js, components/portal/main/services.js, components/portal/misc/services.js, components/portal/timeout/services.js, docs/configuration.md
Heads up, this one's important. 
(The specific line-by-line changes here aren't important. These lines look like bugfixes because they're bugfixes. It's the big picture, the pivot in approach to how login works, that's important.)
Big picture: with improvements to `miscService.redirectUser` it is now preferable to trigger *all* logins via `miscService.redirectUser` or via direct hyperlink to login (in the case of a login button on public.my, say.)
Therefore:
+ Deprecate the undocumented configuration of the "silent" login URL. "Silent" logins in the background on asynchronous requests will work in strictly a subset of the situations in which `miscService.redirectUser` will work.
+ Change default configuration of "silent" login to not be "silent", so that where it is still used it will …
=> Pivot away from asynchronous "silent" login

CHANGELOG.md, components/js/angucomplete.js, components/portal/main/services.js, components/portal/messages/services.js, components/portal/storage/services.js, components/portal/timeout/services.js, components/portal/widgets/controllers.js, components/portal/widgets/services.js
Configure `$http.get` to cache the success responses it gets from the server.
=> Use caching in $http.get consistently

CHANGELOG.md, components/config.js, components/portal/main.js
Configure Angulartics to use Google Tag Manager rather than directly Google Analytics.
Removes the Google Analytics plugin for angulartics.
Adds the Google Tag Manager plugin, the essential bit of it inline rather than as a dependency.
Upgrades to angulartics 1.6.
=> Integrate Angulartics with Google Tag Manager

CHANGELOG.md, docs/upgrading.md
Document the breaking change to viable `MISC_URLS.loginURL` value that tripped up MUMAA on attempt to upgrade `preparing-for-soar`.
=> Document MISC_URLS.loginURL breaking change in 19

CHANGELOG.md, components/head-static.html, components/portal/main/controllers.js, components/portal/main/partials/body.html, components/staticFeeds/sample-banners.json
Upgrades to `myuw-banner` v3.
Expects the API from the new myuw banner backend v2.
Connects these together to offer banner messages with learn more link.
=> Upgrade to myuw-banner 3 with its Learn more link support

CHANGELOG.md, components/portal/misc/services.js
When something calls the redirect method in the misc service passing `undefined` as the status code, err on the side of performing the redirect.
----
=> redirect on status undefined

CHANGELOG.md, components/css/buckyless/widget.less, components/portal/widgets/controllers.js, components/portal/widgets/directives.js, components/portal/widgets/partials/type__weather.html
In some appropriate future release, I'd like `uportal-app-framework` to remove the Weather widget type. We're not using it in MyUW, so I'm not aware of any active adopter in a position to notice when this widget type breaks and maintain it going forward. It'll be cleaner to intentionally remove it than to neglect it.
----
=> docs(deprecation): formally deprecate Weather widget type

CHANGELOG.md, components/portal/misc/services.js
Observed on predev.my infinite redirect on a particular failure of the layout backend.
The layout backend should not, of course, fail.
But if it does fail, the front end shouldn't enter an infinite redirect loop. 
This pull request backs out the change that made the framework more aggressive about redirecting through login on failures. Before this change, undefined responses yielded redirect. After this change, undefined responses don't yield a redirect.
=> stop redirecting through login on status undefined

CHANGELOG.md, components/portal/settings/controllers.js, components/portal/settings/partials/toast-reset-layout.html
This should display the toast message when the reset layout POST request fails.
----
=> Fix reset-fail toast message

CHANGELOG.md, components/portal/main.js
Visual fading out style (slowfade class) was getting applied 1.5 sec sooner than hiding the skeleton (placeholder content used while waiting for the app to get loaded), resulting skeleton being invisible to the users providing confusing experience.
I'm moving `$rootScope.portal.loading.startFade = true;` inside the $timeout so that dading and hiding happens with the same delay.
----
=> Use timeout to delay fading loading placeholder content too early

CHANGELOG.md, components/css/buckyless/md-generated.less
Make tooltips more readable by applying contrasting background
----
=> Make tooltips more readable by applying contrasting background

CHANGELOG.md, components/css/buckyless/general.less, components/css/buckyless/widget.less, components/portal/main/partials/header.html
- Apply focus and hover style to widget action button
- Remove focusable elements from `outline: none` style rule
- 
=> Apply focus & hover style to widget action button

CHANGELOG.md, components/css/buckyless/md-generated.less, components/head-static.html, components/portal/main/partials/header.html
+ Update `myuw-notifications` to v1.4.2
+ Adjust z-index and position of tooltips attached to header buttons so they display with equal distance from the naviggation bar
https://user-images.githubusercontent.com/10341961/156805395-dccd8ce0-0d5e-46ca-9576-19f1551534c5.mov
=> Adjust z-index and position of tooltips attached to header buttons

CHANGELOG.md, components/css/buckyless/md-generated.less, components/head-static.html, components/js/app-config.js, components/portal/main/partials/header.html
+ Update `myuw-feedback` to v1.0.5
+ Set showFeedbackComponent to true, to activate Feedback Web Component in header
----
=> Activate Feedback Web Component in header
